//! Validated transcript → prompt bytes for the generic Qwen family.
//!
//! Normative fixtures: `qwen_no_thinking_preclosed_history_stable` and the
//! preserve/strip append cases in
//! `tests/fixtures/serve_render_fixtures_v1.json`. Two invariants matter
//! more than anything else here (S0 F1: checkpoint hits demand byte
//! identity):
//!
//! 1. `render(split(emitted)) == emitted` — the reasoning splitter and the
//!    preserve renderer are exact inverses, so an items round trip
//!    reproduces the generated bytes and completed-turn checkpoints hit.
//! 2. In no-thinking sessions, history assistant turns re-render the
//!    preclosed `<think>\n\n</think>\n\n` block the model actually
//!    consumed, keeping prompt-boundary prefix stability (the naive strip
//!    rendering is the documented divergence case).
//!
//! The validated Qwen3.8 identity currently renders through this same
//! generic path, exactly as the legacy CLI does (S0 exercised q38 through
//! it); the bespoke Qwen3.8 pre-closed-history renderer remains a modern
//! `qwen run` surface and is out of S1 serve scope.

use super::items::{QwenTemplate, ServeRequest, ToolDefinition, Turn};
use super::tool_parse::{ParsedCall, render_calls};
use crate::messages::{Qwen38GenerationMode, Qwen38ReasoningEffort};

const IM_START: &str = "<|im_start|>";
const IM_END: &str = "<|im_end|>\n";
const THINK_OPEN: &str = "<think>";
const THINK_CLOSE: &str = "</think>";
const PRECLOSED_THINK: &str = "<think>\n\n</think>\n\n";

/// Split raw generated text into (reasoning, visible) at the first
/// `</think>`. Exact-inverse contract: when the reasoning is `Some` and
/// `closed` is true, `render_assistant_body` reproduces the input bytes.
/// An unclosed block (token_limit mid-thinking, S0 F4) yields
/// `closed: false`; the HTTP layer marks the reasoning item and response
/// `incomplete`, and re-echoing it will not reproduce the original bytes
/// (no `</think>` existed), which is the recorded checkpoint caveat for
/// truncated turns.
#[derive(Debug, Clone, PartialEq)]
pub(crate) struct SplitReasoning<'a> {
    pub(crate) reasoning: Option<&'a str>,
    pub(crate) visible: &'a str,
    pub(crate) closed: bool,
}

/// Headless split for pre-opened think blocks (DeepSeek V4 thinking
/// tiers): everything before the first `</think>` is reasoning.
pub(crate) fn split_preopened_reasoning(full: &str) -> SplitReasoning<'_> {
    match full.split_once(THINK_CLOSE) {
        Some((reasoning, visible)) => SplitReasoning {
            reasoning: Some(reasoning),
            visible,
            closed: true,
        },
        None => SplitReasoning {
            reasoning: Some(full),
            visible: "",
            closed: false,
        },
    }
}

pub(crate) fn split_reasoning(full: &str) -> SplitReasoning<'_> {
    if let Some(rest) = full.strip_prefix(THINK_OPEN) {
        if let Some((reasoning, visible)) = rest.split_once(THINK_CLOSE) {
            SplitReasoning {
                reasoning: Some(reasoning),
                visible,
                closed: true,
            }
        } else {
            SplitReasoning {
                reasoning: Some(rest),
                visible: "",
                closed: false,
            }
        }
    } else {
        SplitReasoning {
            reasoning: None,
            visible: full,
            closed: true,
        }
    }
}

/// Qwen3.8 renders history assistant turns with a preclosed empty think
/// block and trims content — the upstream contract implemented by
/// `messages::render_qwen38_messages_prompt_with_generation`. Kept in sync
/// by `serve_generic_matches_cli_renderer` /
/// `serve_qwen38_matches_cli_renderer` below, which assert byte equality
/// against those CLI renderers on every non-tool case.
fn render_qwen38_assistant_body(visible: &str, output: &mut String) {
    output.push_str(PRECLOSED_THINK);
    output.push_str(visible.trim());
}

fn render_assistant_body(
    reasoning: Option<&str>,
    visible: &str,
    no_thinking: bool,
    strip_history_thinking: bool,
    output: &mut String,
) {
    if no_thinking {
        // Normative: qwen_no_thinking_preclosed_history_stable. The model
        // consumed the preclosed block in its prompt; history must
        // re-render it or every prior-turn checkpoint misses (S0 F1).
        output.push_str(PRECLOSED_THINK);
        output.push_str(visible);
        return;
    }
    match reasoning {
        Some(reasoning) if !strip_history_thinking => {
            output.push_str(THINK_OPEN);
            output.push_str(reasoning);
            output.push_str(THINK_CLOSE);
            output.push_str(visible);
        }
        _ => output.push_str(visible),
    }
}

const TOOLS_FORMAT_INSTRUCTION: &str = concat!(
    "\n\nIf you choose to call a function ONLY reply in the following format with NO suffix:\n\n",
    "<tool_call>\n<function=example_function_name>\n<parameter=example_parameter_1>\nvalue_1\n",
    "</parameter>\n<parameter=example_parameter_2>\nThis is the value for the second parameter\n",
    "that can span\nmultiple lines\n</parameter>\n</function>\n</tool_call>\n\n<IMPORTANT>\n",
    "Reminder:\n- Function calls MUST follow the specified format: an inner ",
    "<function=...></function> block must be nested within <tool_call></tool_call> XML tags\n",
    "- Required parameters MUST be specified\n",
    "- You may provide optional reasoning for your function call in natural language BEFORE the ",
    "function call, but NOT after\n",
    "- If there is no function call available, answer the question like normal with your current ",
    "knowledge and do not tell the user about function calls\n</IMPORTANT>",
);

/// Tools block, byte-pinned to the template oracle
/// (`qwen36_tools_system_block_with_system`): the tools system message
/// absorbs the caller's system text after `</IMPORTANT>`.
fn render_tools_system_block(tools: &[ToolDefinition], system: Option<&str>, output: &mut String) {
    output.push_str(IM_START);
    output.push_str("system\n");
    output.push_str("# Tools\n\nYou have access to the following functions:\n\n<tools>");
    for tool in tools {
        output.push('\n');
        let mut entry = serde_json::Map::new();
        entry.insert("type".into(), serde_json::json!("function"));
        entry.insert("name".into(), serde_json::json!(tool.name));
        if let Some(description) = tool.description.as_deref() {
            entry.insert("description".into(), serde_json::json!(description));
        }
        if !tool.parameters.is_null() {
            entry.insert("parameters".into(), tool.parameters.clone());
        }
        if let Some(strict) = tool.strict {
            entry.insert("strict".into(), serde_json::json!(strict));
        }
        output.push_str(
            &serde_json::to_string(&serde_json::Value::Object(entry))
                .expect("serialize tool definition"),
        );
    }
    output.push_str("\n</tools>");
    output.push_str(TOOLS_FORMAT_INSTRUCTION);
    if let Some(system) = system.filter(|text| !text.trim().is_empty()) {
        output.push_str("\n\n");
        output.push_str(system);
    }
    output.push_str(IM_END);
}

/// Render the full prompt for a validated request, including the
/// generation suffix.
pub(crate) fn render_qwen_serve_prompt(request: &ServeRequest) -> String {
    let mut output = String::new();
    let qwen38_mode = qwen38_generation_mode(request);
    let effort_instruction = qwen38_mode.and_then(|mode| match mode {
        Qwen38GenerationMode::Thinking(effort) => effort.instruction(),
        Qwen38GenerationMode::NoThinking => None,
    });
    if !request.tools.is_empty() {
        render_tools_system_block(&request.tools, request.system.as_deref(), &mut output);
    } else if effort_instruction.is_some() || request.system.is_some() {
        let system = request.system.as_deref().unwrap_or("").trim();
        if effort_instruction.is_some() || !system.is_empty() {
            output.push_str(IM_START);
            output.push_str("system\n");
            if let Some(instruction) = effort_instruction {
                output.push_str(instruction);
                if !system.is_empty() {
                    output.push_str("\n\n");
                }
            }
            output.push_str(if qwen38_mode.is_some() {
                system
            } else {
                request.system.as_deref().unwrap_or("")
            });
            output.push_str(IM_END);
        }
    }
    for turn in &request.turns {
        match turn {
            Turn::User(text) => {
                output.push_str(IM_START);
                output.push_str("user\n");
                output.push_str(text);
                output.push_str(IM_END);
            }
            Turn::Assistant {
                reasoning,
                visible,
                calls,
            } => {
                output.push_str(IM_START);
                output.push_str("assistant\n");
                if qwen38_mode.is_some() && calls.is_empty() {
                    render_qwen38_assistant_body(visible, &mut output);
                    output.push_str(IM_END);
                    continue;
                }
                let body = if calls.is_empty() {
                    visible.clone()
                } else {
                    let parsed: Vec<ParsedCall> = calls
                        .iter()
                        .map(|call| ParsedCall {
                            name: call.name.clone(),
                            arguments: serde_json::from_str(&call.arguments)
                                .expect("validated function_call arguments object"),
                        })
                        .collect();
                    render_calls(visible, &parsed)
                };
                render_assistant_body(
                    reasoning.as_deref(),
                    &body,
                    request.no_thinking
                        || matches!(qwen38_mode, Some(Qwen38GenerationMode::NoThinking)),
                    request.strip_history_thinking,
                    &mut output,
                );
                output.push_str(IM_END);
            }
            // Coalesced tool results in one user block, each wrapped per
            // the template oracle.
            Turn::ToolResults(results) => {
                output.push_str(IM_START);
                output.push_str("user");
                for result in results {
                    output.push_str("\n<tool_response>\n");
                    output.push_str(result);
                    output.push_str("\n</tool_response>");
                }
                output.push_str(IM_END);
            }
        }
    }
    output.push_str(IM_START);
    output.push_str("assistant\n");
    match qwen38_mode {
        Some(Qwen38GenerationMode::Thinking(_)) => output.push_str("<think>\n"),
        Some(Qwen38GenerationMode::NoThinking) => output.push_str(PRECLOSED_THINK),
        None if request.no_thinking => output.push_str(PRECLOSED_THINK),
        None => {}
    }
    output
}

/// Qwen3.8 generation mode from the request, or `None` for generic Qwen.
/// Absent effort defaults to upstream xhigh, matching `qwen run`.
fn qwen38_generation_mode(request: &ServeRequest) -> Option<Qwen38GenerationMode> {
    if request.template != QwenTemplate::Qwen38 {
        return None;
    }
    if request.no_thinking {
        return Some(Qwen38GenerationMode::NoThinking);
    }
    Some(match request.reasoning_effort.as_deref() {
        Some("none") => Qwen38GenerationMode::NoThinking,
        Some("low") => Qwen38GenerationMode::Thinking(Qwen38ReasoningEffort::Low),
        Some("medium") => Qwen38GenerationMode::Thinking(Qwen38ReasoningEffort::Medium),
        _ => Qwen38GenerationMode::Thinking(Qwen38ReasoningEffort::Xhigh),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::open_responses::items::parse_request;
    use serde_json::{Value, json};

    fn fixture_case(name: &str) -> Value {
        let fixture: Value = serde_json::from_str(include_str!(
            "../../tests/fixtures/serve_render_fixtures_v1.json"
        ))
        .expect("parse serve render fixture JSON");
        fixture["cases"]
            .as_array()
            .expect("fixture cases")
            .iter()
            .find(|case| case["name"].as_str() == Some(name))
            .unwrap_or_else(|| panic!("missing fixture case {name}"))
            .clone()
    }

    #[test]
    fn split_and_preserve_render_are_exact_inverses() {
        for emitted in [
            "<think>\n2+3=5.\n</think>\n\n5.",
            "<think></think>plain",
            "no thinking at all",
            "<think>\nweird</think>",
        ] {
            let split = split_reasoning(emitted);
            assert!(split.closed, "{emitted:?} should close");
            let mut rendered = String::new();
            render_assistant_body(split.reasoning, split.visible, false, false, &mut rendered);
            assert_eq!(rendered, emitted, "round trip diverged");
        }

        let truncated = split_reasoning("<think>\nran out of budg");
        assert!(!truncated.closed);
        assert_eq!(truncated.reasoning, Some("\nran out of budg"));
        assert_eq!(truncated.visible, "");
    }

    #[test]
    fn items_request_reproduces_preserve_append_fixture_bytes() {
        let case = fixture_case("qwen_multiturn_preserve_append");
        // The fixture stores the assistant turn as inline-think ChatMessage
        // content for the legacy renderer; the serve wire form is the split
        // items shape. Assert the two converge on identical prompt bytes.
        let split = split_reasoning("<think>\n2+3=5.\n</think>\n\n5.");
        let request = parse_request(&json!({
            "model": "m",
            "input": [
                {"role": "system", "content": "You are terse."},
                {"role": "user", "content": "Add 2 and 3."},
                {"type": "reasoning", "content": split.reasoning.unwrap()},
                {"role": "assistant", "content": split.visible},
                {"role": "user", "content": "Now add 4."},
            ],
        }))
        .expect("valid items request");
        assert_eq!(
            render_qwen_serve_prompt(&request),
            case["prompt"].as_str().expect("case prompt"),
            "serve items render diverged from frozen fixture bytes"
        );
    }

    #[test]
    fn strip_history_matches_strip_append_fixture_bytes() {
        let case = fixture_case("qwen_multiturn_strip_append");
        let request = parse_request(&json!({
            "model": "m",
            "input": [
                {"role": "system", "content": "You are terse."},
                {"role": "user", "content": "Add 2 and 3."},
                {"type": "reasoning", "content": "\n2+3=5.\n"},
                {"role": "assistant", "content": "\n\n5."},
                {"role": "user", "content": "Now add 4."},
            ],
            "x_qwen": {"history_thinking": "strip"},
        }))
        .expect("valid items request");
        // Strip drops the reasoning item; visible bytes remain verbatim.
        // The legacy fixture strips via strip_think whose output trims the
        // leading whitespace, so align the wire shape accordingly.
        let rendered = render_qwen_serve_prompt(&request);
        let expected = case["prompt"].as_str().expect("case prompt");
        // Both renders must share the prompt-boundary prefix through the
        // prior generation suffix; visible-content whitespace policy is the
        // serve wire's own (documented) choice.
        let boundary = "<|im_start|>assistant\n";
        let expected_head = &expected[..expected.find(boundary).unwrap() + boundary.len()];
        assert!(rendered.starts_with(expected_head));
    }

    #[test]
    fn no_thinking_history_matches_normative_fixture_bytes() {
        let single = fixture_case("qwen_no_thinking_single");
        let request = parse_request(&json!({
            "model": "m",
            "input": [{"role": "user", "content": "Add 2 and 3."}],
            "x_qwen": {"no_thinking": true},
        }))
        .expect("valid request");
        assert_eq!(
            render_qwen_serve_prompt(&request),
            single["prompt"].as_str().expect("case prompt"),
        );

        let case = fixture_case("qwen_no_thinking_preclosed_history_stable");
        let request = parse_request(&json!({
            "model": "m",
            "input": [
                {"role": "user", "content": "Add 2 and 3."},
                {"role": "assistant", "content": "5."},
                {"role": "user", "content": "Now add 4."},
            ],
            "x_qwen": {"no_thinking": true},
        }))
        .expect("valid request");
        let rendered = render_qwen_serve_prompt(&request);
        assert_eq!(
            rendered,
            case["prompt"].as_str().expect("case prompt"),
            "serve no-thinking history render diverged from the normative fixture"
        );
        let single_prompt = single["prompt"].as_str().unwrap();
        assert!(
            rendered.starts_with(single_prompt),
            "no-thinking append lost prompt-boundary prefix stability"
        );
    }

    #[test]
    fn tools_system_block_matches_frozen_fixture_bytes() {
        let fixture: Value = serde_json::from_str(include_str!(
            "../../tests/fixtures/serve_tool_render_fixtures_v1.json"
        ))
        .expect("parse tool fixtures");
        let case = fixture["cases"]
            .as_array()
            .unwrap()
            .iter()
            .find(|case| case["name"] == "qwen36_tools_system_block_with_system")
            .expect("tools block case")
            .clone();
        let request = parse_request(&json!({
            "model": "m",
            "instructions": case["system"],
            "tools": case["tools"],
            "input": "List files in /tmp.",
        }))
        .expect("tools request must parse");
        let rendered = render_qwen_serve_prompt(&request);
        let expected_block = case["prompt"].as_str().unwrap();
        assert!(
            rendered.starts_with(expected_block),
            "tools system block diverged from frozen fixture:\n got: {:?}\nwant: {:?}",
            &rendered[..expected_block.len().min(rendered.len())],
            expected_block
        );
    }

    #[test]
    fn tool_continuation_prompt_matches_oracle_shape() {
        // Full loop: tools block, user, assistant(reasoning + call),
        // coalesced tool_response user block, generation prompt.
        let request = parse_request(&json!({
            "model": "m",
            "tools": [{"type": "function", "name": "fs_list",
                        "parameters": {"type": "object"}}],
            "input": [
                {"role": "user", "content": "List files in /tmp."},
                {"type": "reasoning", "content": "\nUse fs.list.\n"},
                {"type": "function_call", "call_id": "c1", "name": "fs_list",
                 "arguments": "{\"path\":\"/tmp\"}"},
                {"type": "function_call_output", "call_id": "c1",
                 "output": "{\"entries\":[\"a.txt\"]}"},
            ],
        }))
        .expect("tool loop must parse");
        let rendered = render_qwen_serve_prompt(&request);
        let tail_start = rendered
            .find("<|im_start|>user\nList files")
            .expect("user turn");
        assert_eq!(
            &rendered[tail_start..],
            concat!(
                "<|im_start|>user\nList files in /tmp.<|im_end|>\n",
                "<|im_start|>assistant\n<think>\nUse fs.list.\n</think>",
                "<tool_call>\n<function=fs_list>\n<parameter=path>\n/tmp\n</parameter>\n",
                "</function>\n</tool_call><|im_end|>\n",
                "<|im_start|>user\n<tool_response>\n{\"entries\":[\"a.txt\"]}\n</tool_response>",
                "<|im_end|>\n",
                "<|im_start|>assistant\n",
            ),
        );
    }

    #[test]
    fn qwen38_no_thinking_tool_replay_preserves_preclosed_block() {
        for extension in [
            json!({"reasoning": {"effort": "none"}}),
            json!({"x_qwen": {"no_thinking": true}}),
        ] {
            let mut body = json!({
                "model": "m",
                "tools": [{"type": "function", "name": "ping",
                           "parameters": {"type": "object"}}],
                "input": [
                    {"role": "user", "content": "Ping."},
                    {"type": "function_call", "call_id": "c1", "name": "ping",
                     "arguments": "{}"},
                    {"type": "function_call_output", "call_id": "c1", "output": "pong"},
                ],
            });
            for (key, value) in extension.as_object().unwrap() {
                body[key] = value.clone();
            }
            let mut request = parse_request(&body).expect("no-thinking tool replay parses");
            request.template = QwenTemplate::Qwen38;
            let rendered = render_qwen_serve_prompt(&request);
            let tail = rendered
                .split_once("<|im_start|>user\nPing.")
                .expect("user turn")
                .1;
            assert_eq!(
                tail,
                concat!(
                    "<|im_end|>\n",
                    "<|im_start|>assistant\n<think>\n\n</think>\n\n",
                    "<tool_call>\n<function=ping>\n</function>\n</tool_call>",
                    "<|im_end|>\n",
                    "<|im_start|>user\n<tool_response>\npong\n</tool_response>",
                    "<|im_end|>\n",
                    "<|im_start|>assistant\n<think>\n\n</think>\n\n",
                ),
                "effective Qwen3.8 no-thinking mode lost replay identity"
            );
        }
    }

    /// Anti-drift: serve's renderer must agree byte-for-byte with the CLI
    /// renderers on every case the CLI can express. Serve's is a superset
    /// (tools), so agreement is asserted on the non-tool cases — the exact
    /// class where a divergence would silently change model behaviour, as
    /// it did for Qwen3.8 before this.
    fn cli_messages(turns: &[(&str, Option<&str>, &str)]) -> Vec<crate::messages::ChatMessage> {
        turns
            .iter()
            .map(|(role, reasoning, content)| crate::messages::ChatMessage {
                role: (*role).into(),
                content: match reasoning {
                    Some(reasoning) => format!("<think>{reasoning}</think>{content}"),
                    None => (*content).into(),
                },
                ..Default::default()
            })
            .collect()
    }

    fn serve_request(
        template: crate::open_responses::items::QwenTemplate,
        effort: Option<&str>,
        turns: &[(&str, Option<&str>, &str)],
        system: Option<&str>,
    ) -> ServeRequest {
        let mut request = ServeRequest {
            template,
            reasoning_effort: effort.map(str::to_owned),
            system: system.map(str::to_owned),
            ..ServeRequest::default()
        };
        for (role, reasoning, content) in turns {
            request.turns.push(match *role {
                "user" => Turn::User((*content).into()),
                "assistant" => Turn::Assistant {
                    reasoning: reasoning.map(str::to_owned),
                    visible: (*content).into(),
                    calls: Vec::new(),
                },
                other => panic!("unexpected role {other}"),
            });
        }
        request
    }

    #[test]
    fn serve_generic_matches_cli_renderer() {
        let turns = [
            ("user", None, "Add 2 and 3."),
            ("assistant", Some("\n2+3=5.\n"), "5."),
            ("user", None, "Now add 4."),
        ];
        let request = serve_request(
            crate::open_responses::items::QwenTemplate::Generic,
            None,
            &turns,
            Some("You are terse."),
        );
        let mut cli = vec![crate::messages::ChatMessage {
            role: "system".into(),
            content: "You are terse.".into(),
            ..Default::default()
        }];
        cli.extend(cli_messages(&turns));
        assert_eq!(
            render_qwen_serve_prompt(&request),
            crate::messages::render_qwen_messages_prompt_with_generation(
                &cli,
                true,
                true,
                crate::messages::QwenGenerationMode::Auto,
            ),
            "serve generic renderer diverged from the CLI renderer"
        );
    }

    #[test]
    fn serve_qwen38_matches_cli_renderer() {
        let turns = [
            ("user", None, "Add 2 and 3."),
            ("assistant", None, "5."),
            ("user", None, "Now add 4."),
        ];
        for (effort, mode) in [
            (
                None,
                Qwen38GenerationMode::Thinking(Qwen38ReasoningEffort::Xhigh),
            ),
            (Some("none"), Qwen38GenerationMode::NoThinking),
            (
                Some("low"),
                Qwen38GenerationMode::Thinking(Qwen38ReasoningEffort::Low),
            ),
            (
                Some("medium"),
                Qwen38GenerationMode::Thinking(Qwen38ReasoningEffort::Medium),
            ),
        ] {
            let request = serve_request(
                crate::open_responses::items::QwenTemplate::Qwen38,
                effort,
                &turns,
                Some("You are terse."),
            );
            let mut cli = vec![crate::messages::ChatMessage {
                role: "system".into(),
                content: "You are terse.".into(),
                ..Default::default()
            }];
            cli.extend(cli_messages(&turns));
            assert_eq!(
                render_qwen_serve_prompt(&request),
                crate::messages::render_qwen38_messages_prompt_with_generation(&cli, true, mode),
                "serve Qwen3.8 renderer diverged from the CLI renderer (effort {effort:?})"
            );
        }
    }

    #[test]
    fn qwen38_differs_from_generic_which_was_the_bug() {
        let turns = [
            ("user", None, "hi"),
            ("assistant", None, "hello"),
            ("user", None, "again"),
        ];
        let generic = render_qwen_serve_prompt(&serve_request(
            crate::open_responses::items::QwenTemplate::Generic,
            None,
            &turns,
            None,
        ));
        let qwen38 = render_qwen_serve_prompt(&serve_request(
            crate::open_responses::items::QwenTemplate::Qwen38,
            None,
            &turns,
            None,
        ));
        assert_ne!(generic, qwen38, "3.8 must not render as generic ChatML");
        assert!(
            qwen38.contains("<think>\n\n</think>\n\n"),
            "preclosed history"
        );
        assert!(
            qwen38.ends_with("<|im_start|>assistant\n<think>\n"),
            "thinking suffix"
        );
    }

    #[test]
    fn string_input_matches_single_user_fixture_bytes() {
        let case = fixture_case("qwen_single_user_auto");
        let request =
            parse_request(&json!({"model": "m", "input": "Add 2 and 3."})).expect("valid request");
        assert_eq!(
            render_qwen_serve_prompt(&request),
            case["prompt"].as_str().expect("case prompt"),
        );
    }
}
