//! Validated transcript → prompt bytes for the generic Qwen family.
//!
//! Normative fixtures: `qwen_no_thinking_preclosed_history_stable` and the
//! preserve/strip append cases in
//! `tests/fixtures/serve_render_fixtures_v1.json`. Two invariants matter
//! more than anything else here (S0 F1: checkpoint hits demand byte
//! identity):
//!
//! 1. `render(split(emitted)) == emitted` — the reasoning splitter and the
//!    preserve renderer are exact inverses, so an items round trip
//!    reproduces the generated bytes and completed-turn checkpoints hit.
//! 2. In no-thinking sessions, history assistant turns re-render the
//!    preclosed `<think>\n\n</think>\n\n` block the model actually
//!    consumed, keeping prompt-boundary prefix stability (the naive strip
//!    rendering is the documented divergence case).
//!
//! Pinned templates (`QwenTemplate::verified()`) follow the released Jinja
//! byte for byte where the two invariants above allow: content is trimmed,
//! the generation suffix is always `<think>\n` or the preclosed block (the
//! bare suffix exists only for unpinned ChatML), and preserved reasoning
//! replays in the canonical `<think>\n{reasoning}\n</think>\n\n{content}`
//! form, which is byte-identical to the exact inverse for well-formed
//! output. Oracle: `tests/fixtures/qwen36_chat_template_oracle_v1.json`,
//! rendered by `scripts/reference/render_qwen_chat_template.py`.

use super::items::{QwenTemplate, ServeRequest};
use super::tool_parse::{ParsedCall, render_calls};
use crate::messages::{Qwen38GenerationMode, Qwen38ReasoningEffort};
use crate::model_request::{ToolCall, ToolDefinition, Turn};

const IM_START: &str = "<|im_start|>";
const IM_END: &str = "<|im_end|>";
const THINK_OPEN: &str = "<think>";
const THINK_CLOSE: &str = "</think>";
const PRECLOSED_THINK: &str = "<think>\n\n</think>\n\n";

/// What follows `<|im_start|>assistant\n` in the generation suffix, which
/// also fixes the initial state of the output parser.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum QwenGeneration {
    /// Legacy unpinned ChatML: the model emits `<think>` itself if it wants to.
    Bare,
    /// `<think>\n`: the model continues inside an open think block.
    PreOpen,
    /// `<think>\n\n</think>\n\n`: thinking suppressed.
    PreClosed,
}

/// Resolve the generation suffix for a bound request from its template's
/// released default and the request's explicit controls.
pub(crate) fn qwen_generation(request: &ServeRequest) -> QwenGeneration {
    if request.no_thinking {
        return QwenGeneration::PreClosed;
    }
    match request.template {
        QwenTemplate::Qwen38 => match qwen38_generation_mode(request) {
            Some(Qwen38GenerationMode::NoThinking) => QwenGeneration::PreClosed,
            _ => QwenGeneration::PreOpen,
        },
        QwenTemplate::Qwen36 => QwenGeneration::PreOpen,
        QwenTemplate::Qwen35 => {
            if request.thinking_requested {
                QwenGeneration::PreOpen
            } else {
                QwenGeneration::PreClosed
            }
        }
        QwenTemplate::Generic => {
            if request.thinking_requested {
                QwenGeneration::PreOpen
            } else {
                QwenGeneration::Bare
            }
        }
    }
}

/// Python `str.strip()` semantics, which Jinja's `|trim` delegates to:
/// Unicode `White_Space` plus the U+001C..=U+001F separators that Rust's
/// `str::trim` leaves in place.
pub(crate) fn jinja_trim(text: &str) -> &str {
    text.trim_matches(|c: char| c.is_whitespace() || ('\u{1c}'..='\u{1f}').contains(&c))
}

fn push_open_thinking(output: &mut AnnotatedPromptBuilder, context: SpanContext) {
    let thinking = context.channel(Some(QwenServePromptChannel::Thinking));
    output.push(
        THINK_OPEN,
        QwenServePromptSpanKind::ThinkingChannelStartMarker,
        thinking,
        None,
    );
    output.push(
        "\n",
        QwenServePromptSpanKind::ContentSeparator,
        thinking,
        None,
    );
}

/// Split raw generated text into (reasoning, visible) at the first
/// `</think>`. Exact-inverse contract: when the reasoning is `Some` and
/// `closed` is true, `render_assistant_body` reproduces the input bytes.
/// An unclosed block (token_limit mid-thinking, S0 F4) yields
/// `closed: false`; the HTTP layer marks the reasoning item and response
/// `incomplete`, and re-echoing it will not reproduce the original bytes
/// (no `</think>` existed), which is the recorded checkpoint caveat for
/// truncated turns.
#[derive(Debug, Clone, PartialEq)]
pub(crate) struct SplitReasoning<'a> {
    pub(crate) reasoning: Option<&'a str>,
    pub(crate) visible: &'a str,
    pub(crate) closed: bool,
}

/// Headless split for pre-opened think blocks (DeepSeek V4 thinking
/// tiers): everything before the first `</think>` is reasoning.
pub(crate) fn split_preopened_reasoning(full: &str) -> SplitReasoning<'_> {
    match full.split_once(THINK_CLOSE) {
        Some((reasoning, visible)) => SplitReasoning {
            reasoning: Some(reasoning),
            visible,
            closed: true,
        },
        None => SplitReasoning {
            reasoning: Some(full),
            visible: "",
            closed: false,
        },
    }
}

pub(crate) fn split_reasoning(full: &str) -> SplitReasoning<'_> {
    if let Some(rest) = full.strip_prefix(THINK_OPEN) {
        if let Some((reasoning, visible)) = rest.split_once(THINK_CLOSE) {
            SplitReasoning {
                reasoning: Some(reasoning),
                visible,
                closed: true,
            }
        } else {
            SplitReasoning {
                reasoning: Some(rest),
                visible: "",
                closed: false,
            }
        }
    } else {
        SplitReasoning {
            reasoning: None,
            visible: full,
            closed: true,
        }
    }
}

/// Qwen3.8 renders history assistant turns with a preclosed empty think
/// block and trims content — the upstream contract implemented by
/// `messages::render_qwen38_messages_prompt_with_generation`. Kept in sync
/// by `serve_generic_matches_cli_renderer` /
/// `serve_qwen38_matches_cli_renderer` below, which assert byte equality
/// against those CLI renderers on every non-tool case.
fn render_assistant_body(
    reasoning: Option<&str>,
    visible: &str,
    no_thinking: bool,
    strip_history_thinking: bool,
    output: &mut String,
) {
    if no_thinking {
        // Normative: qwen_no_thinking_preclosed_history_stable. The model
        // consumed the preclosed block in its prompt; history must
        // re-render it or every prior-turn checkpoint misses (S0 F1).
        output.push_str(PRECLOSED_THINK);
        output.push_str(visible);
        return;
    }
    match reasoning {
        Some(reasoning) if !strip_history_thinking => {
            output.push_str(THINK_OPEN);
            output.push_str(reasoning);
            output.push_str(THINK_CLOSE);
            output.push_str(visible);
        }
        _ => output.push_str(visible),
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum QwenServePromptSpanKind {
    MessageStartMarker,
    Role,
    ContentSeparator,
    MessageContent,
    MessageEndMarker,
    GeneratedAssistantStartMarker,
    GeneratedAssistantRole,
    ThinkingChannelStartMarker,
    ThinkingChannelEndMarker,
    ReasoningInstructionContent,
    ToolDefinitionContent,
    AssistantReasoningContent,
    ToolCallContent,
    ToolResultContent,
}

impl QwenServePromptSpanKind {
    pub(crate) const fn as_str(self) -> &'static str {
        match self {
            Self::MessageStartMarker => "message_start_marker",
            Self::Role => "role",
            Self::ContentSeparator => "content_separator",
            Self::MessageContent => "message_content",
            Self::MessageEndMarker => "message_end_marker",
            Self::GeneratedAssistantStartMarker => "generated_assistant_start_marker",
            Self::GeneratedAssistantRole => "generated_assistant_role",
            Self::ThinkingChannelStartMarker => "thinking_channel_start_marker",
            Self::ThinkingChannelEndMarker => "thinking_channel_end_marker",
            Self::ReasoningInstructionContent => "reasoning_instruction_content",
            Self::ToolDefinitionContent => "tool_definition_content",
            Self::AssistantReasoningContent => "assistant_reasoning_content",
            Self::ToolCallContent => "tool_call_content",
            Self::ToolResultContent => "tool_result_content",
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum QwenServePromptRole {
    System,
    User,
    Assistant,
}

impl QwenServePromptRole {
    pub(crate) const fn as_str(self) -> &'static str {
        match self {
            Self::System => "system",
            Self::User => "user",
            Self::Assistant => "assistant",
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum QwenServePromptChannel {
    Thinking,
    ToolCall,
    ToolResult,
}

impl QwenServePromptChannel {
    pub(crate) const fn as_str(self) -> &'static str {
        match self {
            Self::Thinking => "thinking",
            Self::ToolCall => "tool_call",
            Self::ToolResult => "tool_result",
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct QwenServePromptSpan {
    pub(crate) kind: QwenServePromptSpanKind,
    pub(crate) message_index: Option<usize>,
    pub(crate) tool_call_index: Option<usize>,
    pub(crate) role: Option<QwenServePromptRole>,
    pub(crate) channel: Option<QwenServePromptChannel>,
    pub(crate) label: Option<String>,
    pub(crate) byte_start: usize,
    pub(crate) byte_end: usize,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct AnnotatedQwenServePrompt {
    pub(crate) text: String,
    pub(crate) spans: Vec<QwenServePromptSpan>,
}

#[derive(Clone, Copy)]
struct SpanContext {
    message_index: Option<usize>,
    tool_call_index: Option<usize>,
    role: Option<QwenServePromptRole>,
    channel: Option<QwenServePromptChannel>,
}

impl SpanContext {
    const fn message(
        message_index: usize,
        role: QwenServePromptRole,
        channel: Option<QwenServePromptChannel>,
    ) -> Self {
        Self {
            message_index: Some(message_index),
            tool_call_index: None,
            role: Some(role),
            channel,
        }
    }

    const fn generated(channel: Option<QwenServePromptChannel>) -> Self {
        Self {
            message_index: None,
            tool_call_index: None,
            role: Some(QwenServePromptRole::Assistant),
            channel,
        }
    }

    const fn tool_call(self, tool_call_index: usize) -> Self {
        Self {
            tool_call_index: Some(tool_call_index),
            ..self
        }
    }

    const fn channel(self, channel: Option<QwenServePromptChannel>) -> Self {
        Self { channel, ..self }
    }
}

#[derive(Default)]
struct AnnotatedPromptBuilder {
    text: String,
    spans: Vec<QwenServePromptSpan>,
}

impl AnnotatedPromptBuilder {
    fn push(
        &mut self,
        text: &str,
        kind: QwenServePromptSpanKind,
        context: SpanContext,
        label: Option<String>,
    ) {
        if text.is_empty() {
            return;
        }
        let byte_start = self.text.len();
        self.text.push_str(text);
        self.spans.push(QwenServePromptSpan {
            kind,
            message_index: context.message_index,
            tool_call_index: context.tool_call_index,
            role: context.role,
            channel: context.channel,
            label,
            byte_start,
            byte_end: self.text.len(),
        });
    }

    fn finish(self) -> AnnotatedQwenServePrompt {
        AnnotatedQwenServePrompt {
            text: self.text,
            spans: self.spans,
        }
    }
}

const TOOLS_FORMAT_INSTRUCTION: &str = concat!(
    "\n\nIf you choose to call a function ONLY reply in the following format with NO suffix:\n\n",
    "<tool_call>\n<function=example_function_name>\n<parameter=example_parameter_1>\nvalue_1\n",
    "</parameter>\n<parameter=example_parameter_2>\nThis is the value for the second parameter\n",
    "that can span\nmultiple lines\n</parameter>\n</function>\n</tool_call>\n\n<IMPORTANT>\n",
    "Reminder:\n- Function calls MUST follow the specified format: an inner ",
    "<function=...></function> block must be nested within <tool_call></tool_call> XML tags\n",
    "- Required parameters MUST be specified\n",
    "- You may provide optional reasoning for your function call in natural language BEFORE the ",
    "function call, but NOT after\n",
    "- If there is no function call available, answer the question like normal with your current ",
    "knowledge and do not tell the user about function calls\n</IMPORTANT>",
);

/// Tools block, byte-pinned to the template oracle
/// (`qwen36_tools_system_block_with_system`): the tools system message
/// absorbs the caller's system text after `</IMPORTANT>`.
fn render_tools_system_block(
    tools: &[ToolDefinition],
    effort_instruction: Option<&str>,
    trim_system: bool,
    system: Option<&str>,
    system_source: Option<&str>,
    message_index: usize,
    output: &mut AnnotatedPromptBuilder,
) {
    let context = SpanContext::message(message_index, QwenServePromptRole::System, None);
    push_message_header(output, context, false);
    // Qwen3.8 places the reasoning-effort instruction before `# Tools`
    // (qwen38_27b_chat_template.jinja: reasoning_instructions + '\n\n').
    if let Some(instruction) = effort_instruction {
        output.push(
            instruction,
            QwenServePromptSpanKind::ReasoningInstructionContent,
            context.channel(Some(QwenServePromptChannel::Thinking)),
            None,
        );
        output.push(
            "\n\n",
            QwenServePromptSpanKind::ContentSeparator,
            context,
            None,
        );
    }
    let mut tools_content =
        String::from("# Tools\n\nYou have access to the following functions:\n\n<tools>");
    for tool in tools {
        tools_content.push('\n');
        let mut entry = serde_json::Map::new();
        entry.insert("type".into(), serde_json::json!("function"));
        entry.insert("name".into(), serde_json::json!(tool.name));
        if let Some(description) = tool.description.as_deref() {
            entry.insert("description".into(), serde_json::json!(description));
        }
        if !tool.parameters.is_null() {
            entry.insert("parameters".into(), tool.parameters.clone());
        }
        if let Some(strict) = tool.strict {
            entry.insert("strict".into(), serde_json::json!(strict));
        }
        tools_content.push_str(
            &serde_json::to_string(&serde_json::Value::Object(entry))
                .expect("serialize tool definition"),
        );
    }
    tools_content.push_str("\n</tools>");
    tools_content.push_str(TOOLS_FORMAT_INSTRUCTION);
    output.push(
        &tools_content,
        QwenServePromptSpanKind::ToolDefinitionContent,
        context,
        None,
    );
    if let Some(system) = system.filter(|text| !jinja_trim(text).is_empty()) {
        output.push(
            "\n\n",
            QwenServePromptSpanKind::ContentSeparator,
            context,
            None,
        );
        output.push(
            if trim_system {
                jinja_trim(system)
            } else {
                system
            },
            QwenServePromptSpanKind::MessageContent,
            context,
            system_source.map(str::to_owned),
        );
    }
    push_message_end(output, context);
}

fn push_message_header(output: &mut AnnotatedPromptBuilder, context: SpanContext, generated: bool) {
    output.push(
        IM_START,
        if generated {
            QwenServePromptSpanKind::GeneratedAssistantStartMarker
        } else {
            QwenServePromptSpanKind::MessageStartMarker
        },
        context,
        None,
    );
    let role = context.role.expect("message header requires role");
    output.push(
        role.as_str(),
        if generated {
            QwenServePromptSpanKind::GeneratedAssistantRole
        } else {
            QwenServePromptSpanKind::Role
        },
        context,
        None,
    );
    output.push(
        "\n",
        QwenServePromptSpanKind::ContentSeparator,
        context,
        None,
    );
}

fn push_message_end(output: &mut AnnotatedPromptBuilder, context: SpanContext) {
    output.push(
        IM_END,
        QwenServePromptSpanKind::MessageEndMarker,
        context,
        None,
    );
    output.push(
        "\n",
        QwenServePromptSpanKind::ContentSeparator,
        context,
        None,
    );
}

fn push_preclosed_thinking(output: &mut AnnotatedPromptBuilder, context: SpanContext) {
    let thinking = context.channel(Some(QwenServePromptChannel::Thinking));
    output.push(
        THINK_OPEN,
        QwenServePromptSpanKind::ThinkingChannelStartMarker,
        thinking,
        None,
    );
    output.push(
        "\n\n",
        QwenServePromptSpanKind::ContentSeparator,
        thinking,
        None,
    );
    output.push(
        THINK_CLOSE,
        QwenServePromptSpanKind::ThinkingChannelEndMarker,
        thinking,
        None,
    );
    output.push(
        "\n\n",
        QwenServePromptSpanKind::ContentSeparator,
        context,
        None,
    );
}

fn push_visible_and_calls(
    output: &mut AnnotatedPromptBuilder,
    context: SpanContext,
    visible: &str,
    calls: &[ToolCall],
    trim: bool,
) {
    let visible = if trim { jinja_trim(visible) } else { visible };
    output.push(
        visible,
        QwenServePromptSpanKind::MessageContent,
        context,
        None,
    );
    for (call_index, call) in calls.iter().enumerate() {
        let separator = if call_index == 0 {
            (!jinja_trim(visible).is_empty()).then_some("\n\n")
        } else {
            Some("\n")
        };
        if let Some(separator) = separator {
            output.push(
                separator,
                QwenServePromptSpanKind::ContentSeparator,
                context,
                None,
            );
        }
        let parsed = ParsedCall {
            name: call.name.clone(),
            arguments: serde_json::from_str(&call.arguments)
                .expect("validated function_call arguments object"),
        };
        output.push(
            &render_calls("", &[parsed]),
            QwenServePromptSpanKind::ToolCallContent,
            context.tool_call(call_index),
            Some(call.name.clone()),
        );
    }
}

fn push_assistant_body(
    output: &mut AnnotatedPromptBuilder,
    context: SpanContext,
    reasoning: Option<&str>,
    visible: &str,
    calls: &[ToolCall],
    no_thinking: bool,
    strip_history_thinking: bool,
    verified: bool,
) {
    if no_thinking {
        push_preclosed_thinking(output, context);
    } else if let Some(reasoning) = reasoning.filter(|_| !strip_history_thinking) {
        let thinking = context.channel(Some(QwenServePromptChannel::Thinking));
        if verified {
            // Released form: `<think>\n{reasoning|trim}\n</think>\n\n{content}`.
            push_open_thinking(output, context);
            output.push(
                jinja_trim(reasoning),
                QwenServePromptSpanKind::AssistantReasoningContent,
                thinking,
                None,
            );
            output.push(
                "\n",
                QwenServePromptSpanKind::ContentSeparator,
                thinking,
                None,
            );
            output.push(
                THINK_CLOSE,
                QwenServePromptSpanKind::ThinkingChannelEndMarker,
                thinking,
                None,
            );
            output.push(
                "\n\n",
                QwenServePromptSpanKind::ContentSeparator,
                context,
                None,
            );
        } else {
            output.push(
                THINK_OPEN,
                QwenServePromptSpanKind::ThinkingChannelStartMarker,
                thinking,
                None,
            );
            output.push(
                reasoning,
                QwenServePromptSpanKind::AssistantReasoningContent,
                thinking,
                None,
            );
            output.push(
                THINK_CLOSE,
                QwenServePromptSpanKind::ThinkingChannelEndMarker,
                thinking,
                None,
            );
        }
    }
    push_visible_and_calls(output, context, visible, calls, verified);
}

/// Render the full prompt for a validated request, including the
/// generation suffix.
pub(crate) fn render_qwen_serve_prompt(request: &ServeRequest) -> String {
    render_qwen_serve_prompt_annotated(request).text
}

pub(crate) fn render_qwen_serve_prompt_annotated(
    request: &ServeRequest,
) -> AnnotatedQwenServePrompt {
    render_qwen_serve_prompt_annotated_with(request, true)
}

/// Render with or without the trailing generation suffix (transcript-only
/// rendering is used by the census tooling).
pub(crate) fn render_qwen_serve_prompt_annotated_with(
    request: &ServeRequest,
    append_generation: bool,
) -> AnnotatedQwenServePrompt {
    let mut output = AnnotatedPromptBuilder::default();
    let verified = request.template.verified();
    let generation = qwen_generation(request);
    let qwen38_mode = qwen38_generation_mode(request);
    let effort_instruction = qwen38_mode.and_then(|mode| match mode {
        Qwen38GenerationMode::Thinking(effort) => effort.instruction(),
        Qwen38GenerationMode::NoThinking => None,
    });
    let mut message_index = 0;
    if !request.model_request.tools.is_empty() {
        render_tools_system_block(
            &request.model_request.tools,
            effort_instruction,
            verified,
            request.model_request.system.as_deref(),
            request
                .model_request
                .system_source
                .map(|source| source.as_str()),
            message_index,
            &mut output,
        );
        message_index += 1;
    } else if effort_instruction.is_some() || request.model_request.system.is_some() {
        let raw_system = request.model_request.system.as_deref().unwrap_or("");
        let system = if verified {
            jinja_trim(raw_system)
        } else {
            raw_system
        };
        if effort_instruction.is_some() || !jinja_trim(raw_system).is_empty() {
            let context = SpanContext::message(message_index, QwenServePromptRole::System, None);
            push_message_header(&mut output, context, false);
            if let Some(instruction) = effort_instruction {
                output.push(
                    instruction,
                    QwenServePromptSpanKind::ReasoningInstructionContent,
                    context.channel(Some(QwenServePromptChannel::Thinking)),
                    None,
                );
                if !system.is_empty() {
                    output.push(
                        "\n\n",
                        QwenServePromptSpanKind::ContentSeparator,
                        context,
                        None,
                    );
                }
            }
            output.push(
                system,
                QwenServePromptSpanKind::MessageContent,
                context,
                request
                    .model_request
                    .system_source
                    .map(|source| source.as_str().to_owned()),
            );
            push_message_end(&mut output, context);
            message_index += 1;
        }
    }
    let mut pending_tool_labels = Vec::new();
    for turn in &request.model_request.turns {
        match turn {
            Turn::User(text) => {
                let context = SpanContext::message(message_index, QwenServePromptRole::User, None);
                push_message_header(&mut output, context, false);
                let text = if verified {
                    jinja_trim(text)
                } else {
                    text.as_str()
                };
                output.push(text, QwenServePromptSpanKind::MessageContent, context, None);
                push_message_end(&mut output, context);
            }
            Turn::Assistant {
                reasoning,
                visible,
                calls,
            } => {
                let channel = (!calls.is_empty()).then_some(QwenServePromptChannel::ToolCall);
                let context =
                    SpanContext::message(message_index, QwenServePromptRole::Assistant, channel);
                push_message_header(&mut output, context, false);
                if qwen38_mode.is_some() && calls.is_empty() {
                    push_preclosed_thinking(&mut output, context);
                    output.push(
                        jinja_trim(visible),
                        QwenServePromptSpanKind::MessageContent,
                        context,
                        None,
                    );
                } else {
                    push_assistant_body(
                        &mut output,
                        context,
                        reasoning.as_deref(),
                        visible,
                        calls,
                        // History assistant turns re-render the block the
                        // model consumed in this session's generation mode
                        // (preclosed for no-thinking and for Qwen3.5's
                        // released default).
                        generation == QwenGeneration::PreClosed,
                        request.strip_history_thinking,
                        verified,
                    );
                }
                pending_tool_labels = calls.iter().map(|call| call.name.clone()).collect();
                push_message_end(&mut output, context);
            }
            // Coalesced tool results in one user block, each wrapped per
            // the template oracle.
            Turn::ToolResults(results) => {
                let context = SpanContext::message(
                    message_index,
                    QwenServePromptRole::User,
                    Some(QwenServePromptChannel::ToolResult),
                );
                push_message_header(&mut output, context, false);
                for (result_index, result) in results.iter().enumerate() {
                    output.push(
                        if result_index == 0 {
                            "<tool_response>\n"
                        } else {
                            "\n<tool_response>\n"
                        },
                        QwenServePromptSpanKind::ContentSeparator,
                        context,
                        None,
                    );
                    output.push(
                        if verified {
                            jinja_trim(&result.output)
                        } else {
                            result.output.as_str()
                        },
                        QwenServePromptSpanKind::ToolResultContent,
                        context.tool_call(result_index),
                        pending_tool_labels.get(result_index).cloned(),
                    );
                    output.push(
                        "\n</tool_response>",
                        QwenServePromptSpanKind::ContentSeparator,
                        context,
                        None,
                    );
                }
                pending_tool_labels.clear();
                push_message_end(&mut output, context);
            }
        }
        message_index += 1;
    }
    if !append_generation {
        return output.finish();
    }
    let generated = SpanContext::generated(None);
    push_message_header(&mut output, generated, true);
    match generation {
        QwenGeneration::PreOpen => push_open_thinking(&mut output, generated),
        QwenGeneration::PreClosed => push_preclosed_thinking(&mut output, generated),
        QwenGeneration::Bare => {}
    }
    output.finish()
}

/// Qwen3.8 generation mode from the request, or `None` for generic Qwen.
/// Absent effort defaults to upstream xhigh, matching `qwen run`.
fn qwen38_generation_mode(request: &ServeRequest) -> Option<Qwen38GenerationMode> {
    if request.template != QwenTemplate::Qwen38 {
        return None;
    }
    if request.no_thinking {
        return Some(Qwen38GenerationMode::NoThinking);
    }
    Some(match request.reasoning_effort.as_deref() {
        Some("none") => Qwen38GenerationMode::NoThinking,
        Some("low") => Qwen38GenerationMode::Thinking(Qwen38ReasoningEffort::Low),
        Some("medium") => Qwen38GenerationMode::Thinking(Qwen38ReasoningEffort::Medium),
        _ => Qwen38GenerationMode::Thinking(Qwen38ReasoningEffort::Xhigh),
    })
}

pub(crate) fn qwen_serve_generation_mode_name(request: &ServeRequest) -> &'static str {
    match qwen38_generation_mode(request) {
        Some(Qwen38GenerationMode::Thinking(Qwen38ReasoningEffort::Low)) => "thinking_low",
        Some(Qwen38GenerationMode::Thinking(Qwen38ReasoningEffort::Medium)) => "thinking_medium",
        Some(Qwen38GenerationMode::Thinking(Qwen38ReasoningEffort::Xhigh)) => "thinking_xhigh",
        Some(Qwen38GenerationMode::NoThinking) => "no_thinking",
        None if request.no_thinking => "no_thinking",
        None => "auto",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::open_responses::items::parse_request;
    use serde_json::{Value, json};

    fn fixture_case(name: &str) -> Value {
        let fixture: Value = serde_json::from_str(include_str!(
            "../../tests/fixtures/serve_render_fixtures_v1.json"
        ))
        .expect("parse serve render fixture JSON");
        fixture["cases"]
            .as_array()
            .expect("fixture cases")
            .iter()
            .find(|case| case["name"].as_str() == Some(name))
            .unwrap_or_else(|| panic!("missing fixture case {name}"))
            .clone()
    }

    fn assert_complete_annotations(prompt: &AnnotatedQwenServePrompt) {
        let mut byte_end = 0;
        for span in &prompt.spans {
            assert_eq!(span.byte_start, byte_end);
            assert!(span.byte_start < span.byte_end);
            assert!(prompt.text.is_char_boundary(span.byte_start));
            assert!(prompt.text.is_char_boundary(span.byte_end));
            byte_end = span.byte_end;
        }
        assert_eq!(byte_end, prompt.text.len());
    }

    #[test]
    fn split_and_preserve_render_are_exact_inverses() {
        for emitted in [
            "<think>\n2+3=5.\n</think>\n\n5.",
            "<think></think>plain",
            "no thinking at all",
            "<think>\nweird</think>",
        ] {
            let split = split_reasoning(emitted);
            assert!(split.closed, "{emitted:?} should close");
            let mut rendered = String::new();
            render_assistant_body(split.reasoning, split.visible, false, false, &mut rendered);
            assert_eq!(rendered, emitted, "round trip diverged");
        }

        let truncated = split_reasoning("<think>\nran out of budg");
        assert!(!truncated.closed);
        assert_eq!(truncated.reasoning, Some("\nran out of budg"));
        assert_eq!(truncated.visible, "");
    }

    #[test]
    fn items_request_reproduces_preserve_append_fixture_bytes() {
        let case = fixture_case("qwen_multiturn_preserve_append");
        // The fixture stores the assistant turn as inline-think ChatMessage
        // content for the legacy renderer; the serve wire form is the split
        // items shape. Assert the two converge on identical prompt bytes.
        let split = split_reasoning("<think>\n2+3=5.\n</think>\n\n5.");
        let request = parse_request(&json!({
            "model": "m",
            "input": [
                {"role": "system", "content": "You are terse."},
                {"role": "user", "content": "Add 2 and 3."},
                {"type": "reasoning", "content": split.reasoning.unwrap()},
                {"role": "assistant", "content": split.visible},
                {"role": "user", "content": "Now add 4."},
            ],
        }))
        .expect("valid items request");
        assert_eq!(
            render_qwen_serve_prompt(&request),
            case["prompt"].as_str().expect("case prompt"),
            "serve items render diverged from frozen fixture bytes"
        );
    }

    #[test]
    fn developer_and_system_compile_identically_but_retain_source_labels() {
        let developer = parse_request(&json!({
            "model": "m",
            "input": [
                {"role": "developer", "content": "policy"},
                {"role": "user", "content": "request"}
            ]
        }))
        .unwrap();
        let system = parse_request(&json!({
            "model": "m",
            "input": [
                {"role": "system", "content": "policy"},
                {"role": "user", "content": "request"}
            ]
        }))
        .unwrap();
        let developer = render_qwen_serve_prompt_annotated(&developer);
        let system = render_qwen_serve_prompt_annotated(&system);
        assert_eq!(developer.text, system.text);
        assert_eq!(
            developer
                .spans
                .iter()
                .find(|span| {
                    span.kind == QwenServePromptSpanKind::MessageContent
                        && span.role == Some(QwenServePromptRole::System)
                })
                .and_then(|span| span.label.as_deref()),
            Some("developer")
        );
        assert_eq!(
            system
                .spans
                .iter()
                .find(|span| {
                    span.kind == QwenServePromptSpanKind::MessageContent
                        && span.role == Some(QwenServePromptRole::System)
                })
                .and_then(|span| span.label.as_deref()),
            Some("system")
        );
    }

    #[test]
    fn strip_history_matches_strip_append_fixture_bytes() {
        let case = fixture_case("qwen_multiturn_strip_append");
        let request = parse_request(&json!({
            "model": "m",
            "input": [
                {"role": "system", "content": "You are terse."},
                {"role": "user", "content": "Add 2 and 3."},
                {"type": "reasoning", "content": "\n2+3=5.\n"},
                {"role": "assistant", "content": "\n\n5."},
                {"role": "user", "content": "Now add 4."},
            ],
            "x_qwen": {"history_thinking": "strip"},
        }))
        .expect("valid items request");
        // Strip drops the reasoning item; visible bytes remain verbatim.
        // The legacy fixture strips via strip_think whose output trims the
        // leading whitespace, so align the wire shape accordingly.
        let rendered = render_qwen_serve_prompt(&request);
        let expected = case["prompt"].as_str().expect("case prompt");
        // Both renders must share the prompt-boundary prefix through the
        // prior generation suffix; visible-content whitespace policy is the
        // serve wire's own (documented) choice.
        let boundary = "<|im_start|>assistant\n";
        let expected_head = &expected[..expected.find(boundary).unwrap() + boundary.len()];
        assert!(rendered.starts_with(expected_head));
    }

    #[test]
    fn no_thinking_history_matches_normative_fixture_bytes() {
        let single = fixture_case("qwen_no_thinking_single");
        let request = parse_request(&json!({
            "model": "m",
            "input": [{"role": "user", "content": "Add 2 and 3."}],
            "x_qwen": {"no_thinking": true},
        }))
        .expect("valid request");
        assert_eq!(
            render_qwen_serve_prompt(&request),
            single["prompt"].as_str().expect("case prompt"),
        );

        let case = fixture_case("qwen_no_thinking_preclosed_history_stable");
        let request = parse_request(&json!({
            "model": "m",
            "input": [
                {"role": "user", "content": "Add 2 and 3."},
                {"role": "assistant", "content": "5."},
                {"role": "user", "content": "Now add 4."},
            ],
            "x_qwen": {"no_thinking": true},
        }))
        .expect("valid request");
        let rendered = render_qwen_serve_prompt(&request);
        assert_eq!(
            rendered,
            case["prompt"].as_str().expect("case prompt"),
            "serve no-thinking history render diverged from the normative fixture"
        );
        let single_prompt = single["prompt"].as_str().unwrap();
        assert!(
            rendered.starts_with(single_prompt),
            "no-thinking append lost prompt-boundary prefix stability"
        );
    }

    #[test]
    fn tools_system_block_matches_frozen_fixture_bytes() {
        let fixture: Value = serde_json::from_str(include_str!(
            "../../tests/fixtures/serve_tool_render_fixtures_v1.json"
        ))
        .expect("parse tool fixtures");
        let case = fixture["cases"]
            .as_array()
            .unwrap()
            .iter()
            .find(|case| case["name"] == "qwen36_tools_system_block_with_system")
            .expect("tools block case")
            .clone();
        let request = parse_request(&json!({
            "model": "m",
            "instructions": case["system"],
            "tools": case["tools"],
            "input": "List files in /tmp.",
        }))
        .expect("tools request must parse");
        let rendered = render_qwen_serve_prompt(&request);
        let expected_block = case["prompt"].as_str().unwrap();
        assert!(
            rendered.starts_with(expected_block),
            "tools system block diverged from frozen fixture:\n got: {:?}\nwant: {:?}",
            &rendered[..expected_block.len().min(rendered.len())],
            expected_block
        );
    }

    #[test]
    fn tool_continuation_prompt_matches_oracle_shape() {
        // Full loop: tools block, user, assistant(reasoning + call),
        // coalesced tool_response user block, generation prompt.
        let request = parse_request(&json!({
            "model": "m",
            "tools": [{"type": "function", "name": "fs_list",
                        "parameters": {"type": "object"}}],
            "input": [
                {"role": "user", "content": "List files in /tmp."},
                {"type": "reasoning", "content": "\nUse fs.list.\n"},
                {"type": "function_call", "call_id": "c1", "name": "fs_list",
                 "arguments": "{\"path\":\"/tmp\"}"},
                {"type": "function_call_output", "call_id": "c1",
                 "output": "{\"entries\":[\"a.txt\"]}"},
            ],
        }))
        .expect("tool loop must parse");
        let rendered = render_qwen_serve_prompt(&request);
        let tail_start = rendered
            .find("<|im_start|>user\nList files")
            .expect("user turn");
        assert_eq!(
            &rendered[tail_start..],
            concat!(
                "<|im_start|>user\nList files in /tmp.<|im_end|>\n",
                "<|im_start|>assistant\n<think>\nUse fs.list.\n</think>",
                "<tool_call>\n<function=fs_list>\n<parameter=path>\n/tmp\n</parameter>\n",
                "</function>\n</tool_call><|im_end|>\n",
                "<|im_start|>user\n<tool_response>\n{\"entries\":[\"a.txt\"]}\n</tool_response>",
                "<|im_end|>\n",
                "<|im_start|>assistant\n",
            ),
        );
        let annotated = render_qwen_serve_prompt_annotated(&request);
        assert_eq!(annotated.text, rendered);
        assert_complete_annotations(&annotated);
        let call = annotated
            .spans
            .iter()
            .find(|span| span.kind == QwenServePromptSpanKind::ToolCallContent)
            .unwrap();
        assert_eq!(call.message_index, Some(2));
        assert_eq!(call.tool_call_index, Some(0));
        assert_eq!(call.role, Some(QwenServePromptRole::Assistant));
        assert_eq!(call.channel, Some(QwenServePromptChannel::ToolCall));
        assert_eq!(call.label.as_deref(), Some("fs_list"));
        let result = annotated
            .spans
            .iter()
            .find(|span| span.kind == QwenServePromptSpanKind::ToolResultContent)
            .unwrap();
        assert_eq!(result.message_index, Some(3));
        assert_eq!(result.tool_call_index, Some(0));
        assert_eq!(result.role, Some(QwenServePromptRole::User));
        assert_eq!(result.channel, Some(QwenServePromptChannel::ToolResult));
        assert_eq!(result.label.as_deref(), Some("fs_list"));
        assert!(annotated.spans.iter().any(|span| {
            span.kind == QwenServePromptSpanKind::AssistantReasoningContent
                && span.channel == Some(QwenServePromptChannel::Thinking)
        }));
        assert!(annotated.spans.iter().any(|span| {
            span.kind == QwenServePromptSpanKind::GeneratedAssistantStartMarker
                && span.message_index.is_none()
        }));
    }

    #[test]
    fn parallel_same_name_results_retain_call_order_and_unicode_byte_spans() {
        let request = parse_request(&json!({
            "model": "m",
            "tools": [{"type": "function", "name": "fetch"}],
            "input": [
                {"role": "user", "content": "Inspect λ."},
                {"type": "function_call", "call_id": "c1", "name": "fetch",
                 "arguments": "{\"id\":1}"},
                {"type": "function_call", "call_id": "c2", "name": "fetch",
                 "arguments": "{\"id\":2}"},
                {"type": "function_call_output", "call_id": "c2", "output": "β"},
                {"type": "function_call_output", "call_id": "c1", "output": "α"}
            ]
        }))
        .unwrap();
        let annotated = render_qwen_serve_prompt_annotated(&request);
        assert_complete_annotations(&annotated);
        let results = annotated
            .spans
            .iter()
            .filter(|span| span.kind == QwenServePromptSpanKind::ToolResultContent)
            .map(|span| {
                (
                    span.tool_call_index,
                    span.label.as_deref(),
                    &annotated.text[span.byte_start..span.byte_end],
                )
            })
            .collect::<Vec<_>>();
        assert_eq!(
            results,
            vec![(Some(0), Some("fetch"), "α"), (Some(1), Some("fetch"), "β")]
        );
    }

    #[test]
    fn qwen38_no_thinking_tool_replay_preserves_preclosed_block() {
        for extension in [
            json!({"reasoning": {"effort": "none"}}),
            json!({"x_qwen": {"no_thinking": true}}),
        ] {
            let mut body = json!({
                "model": "m",
                "tools": [{"type": "function", "name": "ping",
                           "parameters": {"type": "object"}}],
                "input": [
                    {"role": "user", "content": "Ping."},
                    {"type": "function_call", "call_id": "c1", "name": "ping",
                     "arguments": "{}"},
                    {"type": "function_call_output", "call_id": "c1", "output": "pong"},
                ],
            });
            for (key, value) in extension.as_object().unwrap() {
                body[key] = value.clone();
            }
            let mut request = parse_request(&body).expect("no-thinking tool replay parses");
            request.template = QwenTemplate::Qwen38;
            let rendered = render_qwen_serve_prompt(&request);
            let tail = rendered
                .split_once("<|im_start|>user\nPing.")
                .expect("user turn")
                .1;
            assert_eq!(
                tail,
                concat!(
                    "<|im_end|>\n",
                    "<|im_start|>assistant\n<think>\n\n</think>\n\n",
                    "<tool_call>\n<function=ping>\n</function>\n</tool_call>",
                    "<|im_end|>\n",
                    "<|im_start|>user\n<tool_response>\npong\n</tool_response>",
                    "<|im_end|>\n",
                    "<|im_start|>assistant\n<think>\n\n</think>\n\n",
                ),
                "effective Qwen3.8 no-thinking mode lost replay identity"
            );
        }
    }

    /// qwen38_27b_chat_template.jinja emits `reasoning_instructions + '\n\n'`
    /// before `# Tools`, and trims a caller system message appended after
    /// `</IMPORTANT>`.
    #[test]
    fn qwen38_tools_keep_reasoning_effort_instruction_before_tools() {
        let body = json!({
            "model": "m",
            "reasoning": {"effort": "xhigh"},
            "instructions": "  Be terse.  ",
            "tools": [{"type": "function", "name": "ping",
                       "parameters": {"type": "object"}}],
            "input": [{"role": "user", "content": "Ping."}],
        });
        let mut request = parse_request(&body).expect("qwen38 tools request parses");
        request.template = QwenTemplate::Qwen38;
        let rendered = render_qwen_serve_prompt(&request);
        let xhigh = crate::messages::Qwen38ReasoningEffort::Xhigh
            .instruction()
            .expect("xhigh carries an instruction");
        let expected_head = format!("<|im_start|>system\n{xhigh}\n\n# Tools\n\n");
        assert!(
            rendered.starts_with(&expected_head),
            "reasoning instruction must precede the tools block:\n{rendered}"
        );
        assert!(
            rendered.contains("</IMPORTANT>\n\nBe terse.<|im_end|>\n"),
            "system text after tools must be trimmed:\n{rendered}"
        );
        assert_eq!(rendered.matches(xhigh).count(), 1);
    }

    /// Build the serve request an oracle case describes, or `None` when the
    /// Open Responses layer would reject the shape (a second system item).
    fn oracle_request(template: QwenTemplate, input: &serde_json::Value) -> Option<ServeRequest> {
        let mut request = ServeRequest {
            template,
            no_thinking: input["enable_thinking"] == json!(false),
            thinking_requested: input["enable_thinking"] == json!(true),
            strip_history_thinking: input["preserve_thinking"] != json!(true),
            ..ServeRequest::default()
        };
        let mut systems = Vec::new();
        for message in input["messages"].as_array().expect("messages") {
            let role = message["role"].as_str().expect("role");
            let content = message["content"].as_str().unwrap_or("").to_owned();
            match role {
                "system" | "developer" => systems.push(content),
                "user" => request.model_request.turns.push(Turn::User(content)),
                "assistant" => {
                    let reasoning = message["reasoning_content"].as_str().map(str::to_owned);
                    let (reasoning, visible) = match reasoning {
                        Some(reasoning) => (Some(reasoning), content),
                        None => {
                            // Items carry reasoning separately; inline tags are
                            // what the CLI conversion splits (template rule).
                            let (reasoning, visible) =
                                crate::messages::template_split_think(&content);
                            (reasoning, visible)
                        }
                    };
                    request.model_request.turns.push(Turn::Assistant {
                        reasoning,
                        visible,
                        calls: Vec::new(),
                    });
                }
                other => panic!("unexpected role {other}"),
            }
        }
        if systems.len() > 1 {
            return None;
        }
        request.model_request.system = systems.pop();
        Some(request)
    }

    fn assert_oracle_fixture(
        fixture_json: &str,
        template: QwenTemplate,
        divergences: &[(&str, fn(&str) -> String)],
        expected_checked: usize,
    ) {
        let fixture: serde_json::Value = serde_json::from_str(fixture_json).expect("fixture");
        assert_eq!(fixture["schema"], "qwen.chat_template_oracle");
        let mut checked = 0usize;
        for case in fixture["cases"].as_array().expect("cases") {
            let id = case["id"].as_str().expect("id");
            let expected = case["rendered"].as_str().expect("rendered");
            let Some(request) = oracle_request(template, &case["input"]) else {
                continue;
            };
            let rendered = render_qwen_serve_prompt(&request);
            match divergences.iter().find(|(name, _)| *name == id) {
                Some((_, transform)) => assert_eq!(rendered, transform(expected), "{id}"),
                None => assert_eq!(rendered, expected, "{id}"),
            }
            checked += 1;
        }
        assert_eq!(checked, expected_checked, "oracle case census");
    }

    fn preclose_history(expected: &str) -> String {
        expected.replacen(
            "<|im_start|>assistant\nAnswer one",
            "<|im_start|>assistant\n<think>\n\n</think>\n\nAnswer one",
            1,
        )
    }

    fn preserve_history(expected: &str) -> String {
        expected.replacen(
            "<|im_start|>assistant\nAnswer one",
            "<|im_start|>assistant\n<think>\nthinking\n</think>\n\nAnswer one",
            1,
        )
    }

    /// Digest-verified Qwen3.6 rendering matches the released Jinja byte for
    /// byte on every oracle case except the documented divergence: history
    /// assistant turns in a no-thinking session keep the preclosed block the
    /// model consumed (`qwen_no_thinking_preclosed_history_stable`).
    #[test]
    fn qwen36_matches_jinja_oracle_fixture() {
        assert_oracle_fixture(
            include_str!("../../tests/fixtures/qwen36_chat_template_oracle_v1.json"),
            QwenTemplate::Qwen36,
            &[("history_no_thinking_mode", preclose_history)],
            15,
        );
    }

    /// Qwen3.5's released template has no `preserve_thinking`; it strips all
    /// prior reasoning and, by default, suppresses thinking. Serve keeps its
    /// prefix-stability policy for history (preclosed in the default
    /// no-thinking session, canonical replay under preserve), which are the
    /// two documented divergences here.
    #[test]
    fn qwen35_matches_jinja_oracle_fixture() {
        assert_oracle_fixture(
            include_str!("../../tests/fixtures/qwen35_chat_template_oracle_v1.json"),
            QwenTemplate::Qwen35,
            &[
                ("history_default", preclose_history),
                ("history_explicit_thinking_preserve", preserve_history),
            ],
            5,
        );
    }

    /// The generation suffix and the output parser's initial state agree.
    #[test]
    fn generation_suffix_matches_parser_initial_state() {
        for (template, no_thinking, thinking_requested, expected) in [
            (QwenTemplate::Qwen36, false, false, QwenGeneration::PreOpen),
            (QwenTemplate::Qwen36, true, false, QwenGeneration::PreClosed),
            (
                QwenTemplate::Qwen35,
                false,
                false,
                QwenGeneration::PreClosed,
            ),
            (QwenTemplate::Qwen35, false, true, QwenGeneration::PreOpen),
            (QwenTemplate::Generic, false, false, QwenGeneration::Bare),
            (QwenTemplate::Generic, false, true, QwenGeneration::PreOpen),
            (QwenTemplate::Qwen38, false, false, QwenGeneration::PreOpen),
        ] {
            let request = ServeRequest {
                template,
                no_thinking,
                thinking_requested,
                ..ServeRequest::default()
            };
            assert_eq!(qwen_generation(&request), expected, "{template:?}");
            let rendered = render_qwen_serve_prompt(&request);
            let tail = rendered.rsplit_once("<|im_start|>assistant\n").unwrap().1;
            match expected {
                QwenGeneration::PreOpen => assert_eq!(tail, "<think>\n"),
                QwenGeneration::PreClosed => assert_eq!(tail, PRECLOSED_THINK),
                QwenGeneration::Bare => assert_eq!(tail, ""),
            }
        }
    }

    /// Anti-drift: serve's renderer must agree byte-for-byte with the CLI
    /// renderers on every case the CLI can express. Serve's is a superset
    /// (tools), so agreement is asserted on the non-tool cases — the exact
    /// class where a divergence would silently change model behaviour, as
    /// it did for Qwen3.8 before this.
    fn cli_messages(turns: &[(&str, Option<&str>, &str)]) -> Vec<crate::messages::ChatMessage> {
        turns
            .iter()
            .map(|(role, reasoning, content)| crate::messages::ChatMessage {
                role: (*role).into(),
                content: match reasoning {
                    Some(reasoning) => format!("<think>{reasoning}</think>{content}"),
                    None => (*content).into(),
                },
                ..Default::default()
            })
            .collect()
    }

    fn serve_request(
        template: crate::open_responses::items::QwenTemplate,
        effort: Option<&str>,
        turns: &[(&str, Option<&str>, &str)],
        system: Option<&str>,
    ) -> ServeRequest {
        let mut request = ServeRequest {
            template,
            reasoning_effort: effort.map(str::to_owned),
            ..ServeRequest::default()
        };
        request.model_request.system = system.map(str::to_owned);
        for (role, reasoning, content) in turns {
            request.model_request.turns.push(match *role {
                "user" => Turn::User((*content).into()),
                "assistant" => Turn::Assistant {
                    reasoning: reasoning.map(str::to_owned),
                    visible: (*content).into(),
                    calls: Vec::new(),
                },
                other => panic!("unexpected role {other}"),
            });
        }
        request
    }

    #[test]
    fn serve_generic_matches_cli_renderer() {
        let turns = [
            ("user", None, "Add 2 and 3."),
            ("assistant", Some("\n2+3=5.\n"), "5."),
            ("user", None, "Now add 4."),
        ];
        let request = serve_request(
            crate::open_responses::items::QwenTemplate::Generic,
            None,
            &turns,
            Some("You are terse."),
        );
        let mut cli = vec![crate::messages::ChatMessage {
            role: "system".into(),
            content: "You are terse.".into(),
            ..Default::default()
        }];
        cli.extend(cli_messages(&turns));
        assert_eq!(
            render_qwen_serve_prompt(&request),
            crate::messages::render_qwen_messages_prompt_with_generation(
                &cli,
                true,
                true,
                crate::messages::QwenGenerationMode::Auto,
            ),
            "serve generic renderer diverged from the CLI renderer"
        );
    }

    #[test]
    fn serve_qwen38_matches_cli_renderer() {
        let turns = [
            ("user", None, "Add 2 and 3."),
            ("assistant", None, "5."),
            ("user", None, "Now add 4."),
        ];
        for (effort, mode) in [
            (
                None,
                Qwen38GenerationMode::Thinking(Qwen38ReasoningEffort::Xhigh),
            ),
            (Some("none"), Qwen38GenerationMode::NoThinking),
            (
                Some("low"),
                Qwen38GenerationMode::Thinking(Qwen38ReasoningEffort::Low),
            ),
            (
                Some("medium"),
                Qwen38GenerationMode::Thinking(Qwen38ReasoningEffort::Medium),
            ),
        ] {
            let request = serve_request(
                crate::open_responses::items::QwenTemplate::Qwen38,
                effort,
                &turns,
                Some("You are terse."),
            );
            let mut cli = vec![crate::messages::ChatMessage {
                role: "system".into(),
                content: "You are terse.".into(),
                ..Default::default()
            }];
            cli.extend(cli_messages(&turns));
            assert_eq!(
                render_qwen_serve_prompt(&request),
                crate::messages::render_qwen38_messages_prompt_with_generation(&cli, true, mode),
                "serve Qwen3.8 renderer diverged from the CLI renderer (effort {effort:?})"
            );
        }
    }

    #[test]
    fn qwen38_differs_from_generic_which_was_the_bug() {
        let turns = [
            ("user", None, "hi"),
            ("assistant", None, "hello"),
            ("user", None, "again"),
        ];
        let generic = render_qwen_serve_prompt(&serve_request(
            crate::open_responses::items::QwenTemplate::Generic,
            None,
            &turns,
            None,
        ));
        let qwen38 = render_qwen_serve_prompt(&serve_request(
            crate::open_responses::items::QwenTemplate::Qwen38,
            None,
            &turns,
            None,
        ));
        assert_ne!(generic, qwen38, "3.8 must not render as generic ChatML");
        assert!(
            qwen38.contains("<think>\n\n</think>\n\n"),
            "preclosed history"
        );
        assert!(
            qwen38.ends_with("<|im_start|>assistant\n<think>\n"),
            "thinking suffix"
        );
    }

    #[test]
    fn string_input_matches_single_user_fixture_bytes() {
        let case = fixture_case("qwen_single_user_auto");
        let request =
            parse_request(&json!({"model": "m", "input": "Add 2 and 3."})).expect("valid request");
        assert_eq!(
            render_qwen_serve_prompt(&request),
            case["prompt"].as_str().expect("case prompt"),
        );
    }
}
