//! Map #12's natural-trajectory fixture (`scripts/reference/glm53/
//! reuse-natural-v1.json`) through serve's own request and output paths,
//! on the CPU: each case's first turn must render to the fixture's first
//! turn; its generated bytes go through the real output partition and the
//! non-stream response builder; and the second turn, replayed both as the
//! response's own output items and in the patched opencode client's item
//! shapes, must render to the fixture's second turn, which extends the
//! first turn and the consumed tokens (the condition for live-session
//! reuse). The engine harness is `glm5_next_metal::tests::natural`.
use super::*;
use crate::serve::events::{StopReason, Usage, build_response_object};
use crate::serve::output_partition::{GenerationEnd, OutputPartition};
use crate::serve::request_profile::RequestProfile;
use serde_json::{Value, json};

const PROFILE: RequestProfile = RequestProfile::Glm5Next {
    default_max_tokens: 4096,
    capacity: 1 << 20,
    max_piece_bytes: 64,
};

fn bound(body: &Value) -> (ServeRequest, String) {
    let mut request = PROFILE
        .parse(body)
        .unwrap_or_else(|e| panic!("parse: {e:?}"));
    PROFILE
        .normalize(&mut request)
        .unwrap_or_else(|e| panic!("normalize: {e:?}"));
    let prompt = PROFILE
        .render(&request)
        .unwrap_or_else(|e| panic!("render: {e:?}"));
    (request, prompt)
}

fn ids(value: &Value) -> Vec<i32> {
    value
        .as_str()
        .unwrap()
        .split_whitespace()
        .map(|t| t.parse().unwrap())
        .collect()
}

/// The first turn's Responses body: system as instructions, the user turn,
/// the declared tools and the effort.
fn first_body(case: &Value) -> (Value, Vec<Value>) {
    let messages = case["conversation"]["messages"].as_array().unwrap();
    let mut input = Vec::new();
    let mut body = json!({"model": "glm", "reasoning": {"effort": case["effort"]}});
    for message in messages {
        match message["role"].as_str().unwrap() {
            "system" => body["instructions"] = message["content"].clone(),
            "user" => {
                input.push(json!({"role": "user", "content": message["content"]}));
                break;
            }
            other => panic!("unexpected first-turn role {other}"),
        }
    }
    if let Some(tools) = case["conversation"]["tools"].as_array() {
        body["tools"] = tools
            .iter()
            .map(|t| json!({"type": "function", "name": t["name"], "description": t["description"], "parameters": t["parameters"]}))
            .collect();
    }
    body["input"] = json!(input);
    (body, input)
}

/// What the patched opencode client sends back for a response's output
/// items (`docs/bench/2026-10-06-opencode-reasoning-replay/`): reasoning as
/// `reasoning_text` content with an empty summary, assistant text as an
/// output_text message, calls as function_call items.
fn client_shape(item: &Value) -> Value {
    match item["type"].as_str().unwrap() {
        "reasoning" => json!({"type": "reasoning", "summary": [],
            "content": [{"type": "reasoning_text", "text": item["content"][0]["text"]}]}),
        "message" => json!({"role": "assistant",
            "content": [{"type": "output_text", "text": item["content"][0]["text"]}]}),
        "function_call" => json!({"type": "function_call", "call_id": item["call_id"],
            "name": item["name"], "arguments": item["arguments"]}),
        other => panic!("unexpected output item {other}"),
    }
}

#[test]
fn natural_fixture_replays_through_serve() {
    let fixture_path = std::env::var_os("GLM53_REUSE_NATURAL")
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|| {
            std::path::PathBuf::from(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/../../scripts/reference/glm53/reuse-natural-v1.json"
            ))
        });
    let Ok(bytes) = std::fs::read(&fixture_path) else {
        eprintln!("skipped: no fixture at {}", fixture_path.display());
        return;
    };
    let Some(path) = qwen_llm::test_fixtures::GLM53_FLASH_UD_IQ3_XXS.path_or_skip() else {
        return;
    };
    let fixture: Value = serde_json::from_slice(&bytes).unwrap();
    let gguf = qwen_llm::gguf::GgufFile::open(&path).unwrap();
    let tokenizer = qwen_llm::tokenizer::Tokenizer::from_gguf(&gguf).unwrap();
    let encode = |text: &str| tokenizer.encode(text, false).unwrap();
    let cases = fixture["cases"].as_array().unwrap();
    assert!(!cases.is_empty());
    for case in cases {
        let id = case["id"].as_str().unwrap();
        let turn1 = ids(&case["turn1"]);
        let emitted = ids(&case["emitted"]);
        let consumed = &emitted[..case["consumed"].as_u64().unwrap() as usize];
        let stop = case["stop"].as_i64().expect("a stop") as i32;
        let turn2: Vec<i32> = [turn1.as_slice(), consumed, &ids(&case["suffix"])].concat();

        let (body1, input1) = first_body(case);
        let (request1, prompt1) = bound(&body1);
        assert_eq!(
            encode(&prompt1),
            turn1,
            "{id}: serve renders a different first turn"
        );

        // Generated bytes through the real partition and response builder.
        let mut partition = OutputPartition::new(PROFILE.output(&request1));
        let mut events = Vec::new();
        partition.push(tokenizer.decode(consumed).as_bytes(), &mut events);
        partition
            .finish(GenerationEnd::StopToken(stop), &mut events)
            .unwrap_or_else(|e| panic!("{id}: partition finish: {e:?}"));
        let response = build_response_object(
            &request1,
            "resp_natural".into(),
            1,
            &events,
            StopReason::Eos,
            Usage::default(),
            None,
        )
        .unwrap();
        let output = response["output"].as_array().unwrap();

        // The next turn: the second turn's last message.
        let messages = case["conversation"]["messages"].as_array().unwrap();
        let last = messages.last().unwrap();
        let next = match last["role"].as_str().unwrap() {
            "user" => json!({"role": "user", "content": last["content"]}),
            "tool" => {
                let call_id = output
                    .iter()
                    .find(|item| item["type"] == "function_call")
                    .unwrap_or_else(|| panic!("{id}: no published call"))["call_id"]
                    .clone();
                json!({"type": "function_call_output", "call_id": call_id, "output": last["content"]})
            }
            other => panic!("{id}: unexpected last role {other}"),
        };
        for (shape, replayed) in [
            ("output items", output.clone()),
            ("patched client", output.iter().map(client_shape).collect()),
        ] {
            let mut input = input1.clone();
            input.extend(replayed);
            input.push(next.clone());
            let mut body2 = body1.clone();
            body2["input"] = json!(input);
            let (_, prompt2) = bound(&body2);
            let tokens = encode(&prompt2);
            let at = tokens.iter().zip(&turn2).position(|(a, b)| a != b);
            assert_eq!(
                tokens, turn2,
                "{id} ({shape}): serve renders a different second turn (first difference at {at:?})"
            );
        }
        eprintln!(
            "{id}: serve renders the first turn ({} tokens) and, from its own output, the second turn ({} tokens) exactly",
            turn1.len(),
            turn2.len()
        );
    }
}
