//! GLM-5.3-Flash tool calls in generated output.
//!
//! The model writes calls after `</think>`, right after any visible text, in
//! the template's format with no separators,
//! `<tool_call>{name}<arg_key>{k}</arg_key><arg_value>{v}</arg_value>…</tool_call>`,
//! back to back, and ends the turn by sampling `<|observation|>` (a stop).
//! [`ToolOutputStream`] receives post-reasoning visible text only: it
//! releases text before the first `<tool_call>` (holding back a possible
//! marker prefix), buffers the rest within a byte budget, and publishes calls
//! together once the whole block parses. ASCII whitespace is tolerated
//! between calls and around argument markers; any other text after the
//! first call, an undeclared function, a repeated key or a value that does
//! not fit its schema is an error, never salvaged as text.
//!
//! Argument values take their outer type from the declared schema
//! ([`crate::tool_schema::strict_argument_kinds`]; outer types only, not
//! full JSON Schema validation):
//! - schema admits no string: the raw text must decode (losslessly,
//!   duplicate keys refused) as JSON of an admitted, renderable type;
//! - schema admits a string and the text decodes as no other admitted
//!   type: the raw text is the string;
//! - schema admits a string and the text also decodes as another admitted
//!   type (`3` under `{}` or `["string", "integer"]`): the template writes
//!   both identically, so the call is refused as ambiguous rather than
//!   guessed (K2's rule); declare a narrower schema.
//!
//! A parsed value re-renders to the generated bytes when the model wrote it
//! in `tojson`'s canonical form; other JSON forms (`["a","b"]`) are accepted
//! and re-render canonically, and tolerated whitespace is not kept.

use super::tools::{tools, valid_argument_key, valid_tool_name};
use super::*;
use crate::tool_schema::{
    ANY, STRING, decode_json, python_json, strict_argument_kinds, value_kind,
};
use serde_json::{Map, Value};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ToolOutputEnd {
    /// A released stop (`<|observation|>` after calls).
    Stop,
    /// The output token budget ran out.
    TokenLimit,
}

/// A parsed call; the caller assigns its id.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct OutputCall {
    pub name: String,
    pub arguments: Map<String, Value>,
}

#[derive(Debug, PartialEq)]
pub struct ToolOutputFinish {
    /// Visible text held back at the end (a marker prefix that never completed).
    pub visible_tail: String,
    pub calls: Vec<OutputCall>,
    /// A tool block was open when the token budget ran out; no call published.
    pub incomplete_tool_block: bool,
}

enum Parsed {
    Complete(Vec<OutputCall>),
    Incomplete,
}

/// Parse a block that starts at `<tool_call>`.
fn parse_block(block: &str, definitions: &[ToolDefinition]) -> Result<Parsed> {
    let mut rest = block;
    let mut calls = Vec::new();
    loop {
        rest = rest.trim_start_matches(|c: char| c.is_ascii_whitespace());
        if rest.is_empty() {
            return Ok(if calls.is_empty() {
                Parsed::Incomplete
            } else {
                Parsed::Complete(calls)
            });
        }
        let Some(after_open) = rest.strip_prefix(TOOL_CALL_OPEN) else {
            if TOOL_CALL_OPEN.starts_with(rest) {
                return Ok(Parsed::Incomplete);
            }
            return Err(tools("generated text after a tool call is not a tool call"));
        };
        match parse_call(after_open, definitions)? {
            Some((call, remaining)) => {
                calls.push(call);
                rest = remaining;
            }
            None => return Ok(Parsed::Incomplete),
        }
    }
}

/// One call after `<tool_call>`: the call and the text after its
/// `</tool_call>`, or `None` when the text ends first.
fn parse_call<'t>(
    text: &'t str,
    definitions: &[ToolDefinition],
) -> Result<Option<(OutputCall, &'t str)>> {
    let name_end = [ARG_KEY_OPEN, TOOL_CALL_CLOSE]
        .iter()
        .filter_map(|marker| text.find(marker))
        .min();
    let Some(name_end) = name_end else {
        // No marker yet: incomplete while the text can still become
        // `{name}<arg_key>` or `{name}</tool_call>`, separator whitespace on
        // either side of the name included.
        let name = &text[..text.find('<').unwrap_or(text.len())];
        let marker = &text[name.len()..];
        let name = name.trim_matches(|c: char| c.is_ascii_whitespace());
        let name_prefix = name.len() <= 64
            && name
                .bytes()
                .all(|b| b.is_ascii_alphanumeric() || matches!(b, b'_' | b'.' | b'-'));
        let marker_prefix = ARG_KEY_OPEN.starts_with(marker) || TOOL_CALL_CLOSE.starts_with(marker);
        return if name_prefix && marker_prefix {
            Ok(None)
        } else {
            Err(tools("generated tool call name is malformed"))
        };
    };
    let name = text[..name_end].trim_matches(|c: char| c.is_ascii_whitespace());
    if !valid_tool_name(name) {
        return Err(tools(format!(
            "generated tool call name {name:?} is malformed"
        )));
    }
    let definition = definitions
        .iter()
        .find(|d| d.name() == name)
        .ok_or_else(|| {
            tools(format!(
                "generated tool call {name:?} names no declared tool"
            ))
        })?;
    let mut rest = &text[name_end..];
    let mut arguments = Map::new();
    loop {
        rest = rest.trim_start_matches(|c: char| c.is_ascii_whitespace());
        if let Some(after) = rest.strip_prefix(TOOL_CALL_CLOSE) {
            let call = OutputCall {
                name: name.into(),
                arguments,
            };
            return Ok(Some((call, after)));
        }
        let Some(after_key_open) = rest.strip_prefix(ARG_KEY_OPEN) else {
            if ARG_KEY_OPEN.starts_with(rest) || TOOL_CALL_CLOSE.starts_with(rest) {
                return Ok(None);
            }
            return Err(tools("generated tool call arguments are malformed"));
        };
        let Some(key_end) = after_key_open.find(ARG_KEY_CLOSE) else {
            return Ok(None);
        };
        let key = &after_key_open[..key_end];
        if !valid_argument_key(key) {
            return Err(tools(format!(
                "generated argument key {key:?} is malformed"
            )));
        }
        let after_key = after_key_open[key_end + ARG_KEY_CLOSE.len()..]
            .trim_start_matches(|c: char| c.is_ascii_whitespace());
        let Some(after_value_open) = after_key.strip_prefix(ARG_VALUE_OPEN) else {
            if ARG_VALUE_OPEN.starts_with(after_key) {
                return Ok(None);
            }
            return Err(tools(format!("generated argument {key:?} has no value")));
        };
        let Some(value_end) = after_value_open.find(ARG_VALUE_CLOSE) else {
            return Ok(None);
        };
        let raw = &after_value_open[..value_end];
        let value = typed_argument(definition, key, raw)?;
        if arguments.insert(key.into(), value).is_some() {
            return Err(tools(format!("generated argument {key:?} repeats")));
        }
        rest = &after_value_open[value_end + ARG_VALUE_CLOSE.len()..];
    }
}

/// The argument value for `raw` under the declared schema (module rules).
fn typed_argument(definition: &ToolDefinition, key: &str, raw: &str) -> Result<Value> {
    let mask = match definition.parameters() {
        Some(parameters) => strict_argument_kinds(parameters, key).map_err(tools)?,
        None => ANY,
    };
    let decoded = decode_json(raw)
        .ok()
        .filter(|v| !v.is_string() && value_kind(v) & mask != 0 && python_json(v).is_ok());
    match (mask & STRING != 0, decoded) {
        (false, Some(value)) => Ok(value),
        (false, None) => Err(tools(format!(
            "generated argument {key:?} does not encode its declared type"
        ))),
        (true, None) => Ok(Value::String(raw.into())),
        (true, Some(_)) => Err(tools(format!(
            "generated argument {key:?} is ambiguous: its schema admits a string and the text \
             also encodes another admitted type; declare a narrower schema"
        ))),
    }
}

/// Post-reasoning visible text in, visible text and finally calls out.
pub struct ToolOutputStream {
    definitions: Vec<ToolDefinition>,
    max_tool_bytes: usize,
    pending: String,
    block: Option<String>,
    failed: bool,
}

impl ToolOutputStream {
    /// `max_tool_bytes` bounds the buffered tool block (the caller's output
    /// resource admission).
    pub fn new(definitions: Vec<ToolDefinition>, max_tool_bytes: usize) -> Self {
        Self {
            definitions,
            max_tool_bytes,
            pending: String::new(),
            block: None,
            failed: false,
        }
    }

    /// Visible text to release now. Tool bytes never leave as text. Errors
    /// poison the stream.
    pub fn push_visible(&mut self, text: &str) -> Result<String> {
        if self.failed {
            return Err(tools("tool output stream is failed"));
        }
        if self.block.is_some() {
            self.append_block(text)?;
            return Ok(String::new());
        }
        let mut released = std::mem::take(&mut self.pending);
        let mut combined = std::mem::take(&mut released);
        combined.push_str(text);
        if let Some(index) = combined.find(TOOL_CALL_OPEN) {
            self.begin_block(&combined[index..])?;
            released.push_str(&combined[..index]);
            return Ok(released);
        }
        let keep = (1..TOOL_CALL_OPEN.len())
            .rev()
            .find(|&n| combined.ends_with(&TOOL_CALL_OPEN[..n]))
            .unwrap_or(0);
        let safe = combined.len() - keep;
        self.pending.push_str(&combined[safe..]);
        released.push_str(&combined[..safe]);
        Ok(released)
    }

    fn begin_block(&mut self, text: &str) -> Result<()> {
        if text.len() > self.max_tool_bytes {
            self.failed = true;
            return Err(tools("tool output exceeds the admitted byte budget"));
        }
        self.block = Some(text.to_owned());
        Ok(())
    }

    fn append_block(&mut self, text: &str) -> Result<()> {
        let block = self.block.as_mut().unwrap();
        if block
            .len()
            .checked_add(text.len())
            .is_none_or(|n| n > self.max_tool_bytes)
        {
            self.failed = true;
            block.clear();
            return Err(tools("tool output exceeds the admitted byte budget"));
        }
        block.push_str(text);
        Ok(())
    }

    /// Publish the calls once the whole terminal block is known. A complete
    /// block at the token limit still publishes; the caller marks the
    /// response budget-incomplete.
    pub fn finish(self, end: ToolOutputEnd) -> Result<ToolOutputFinish> {
        if self.failed {
            return Err(tools("tool output stream is failed"));
        }
        let Some(block) = self.block else {
            return Ok(ToolOutputFinish {
                visible_tail: self.pending,
                calls: Vec::new(),
                incomplete_tool_block: false,
            });
        };
        match parse_block(&block, &self.definitions)? {
            Parsed::Complete(calls) => Ok(ToolOutputFinish {
                visible_tail: String::new(),
                calls,
                incomplete_tool_block: false,
            }),
            Parsed::Incomplete if end == ToolOutputEnd::TokenLimit => Ok(ToolOutputFinish {
                visible_tail: String::new(),
                calls: Vec::new(),
                incomplete_tool_block: true,
            }),
            Parsed::Incomplete => Err(tools("the turn stopped inside a tool call")),
        }
    }
}

/// Parse a complete generated block (from `<tool_call>`), as at a stop.
pub fn parse_tool_calls(block: &str, definitions: &[ToolDefinition]) -> Result<Vec<OutputCall>> {
    match parse_block(block, definitions)? {
        Parsed::Complete(calls) => Ok(calls),
        Parsed::Incomplete => Err(tools("the tool block is incomplete")),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn weather() -> ToolDefinition {
        ToolDefinition::from_value(&json!({"name": "get_weather", "parameters": {
            "type": "object",
            "properties": {
                "city": {"type": "string"},
                "days": {"type": "integer"},
                "tags": {"type": "array"},
                "any": {}
            }
        }}))
        .unwrap()
    }

    /// Every argument of the typed round-trip case, each with its own type.
    fn typed() -> ToolDefinition {
        ToolDefinition::from_value(
            &json!({"name": "f", "parameters": {"type": "object", "properties": {
                "i": {"type": "integer"}, "neg": {"type": "integer"}, "x": {"type": "number"},
                "big": {"type": "number"}, "small": {"type": "number"}, "t": {"type": "boolean"},
                "n": {"type": "null"}, "list": {"type": "array"}, "obj": {"type": "object"},
                "numeric_string": {"type": "string"}, "unicode": {"type": "string"},
                "multiline": {"type": "string"}, "plain": {"type": "string"}
            }}}),
        )
        .unwrap()
    }

    fn untyped() -> ToolDefinition {
        ToolDefinition::from_value(&json!({"name": "f", "parameters": {"type": "object"}})).unwrap()
    }

    fn one_arg(value: &str) -> String {
        format!("<tool_call>f<arg_key>a</arg_key><arg_value>{value}</arg_value></tool_call>")
    }

    fn schema_for_a(schema: serde_json::Value) -> ToolDefinition {
        ToolDefinition::from_value(
            &json!({"name": "f", "parameters": {"properties": {"a": schema}}}),
        )
        .unwrap()
    }

    /// Text the template writes identically for a string and another
    /// admitted type is refused, not guessed; unambiguous text under an open
    /// schema is a string. Decoding is lossless and values must render.
    #[test]
    fn ambiguous_lossy_or_unrenderable_arguments_are_refused() {
        for ambiguous in ["3", "true", "null", "[1, 2]", r#"{"k": 1}"#] {
            let error = parse_tool_calls(&one_arg(ambiguous), &[untyped()]).unwrap_err();
            assert!(
                error.to_string().contains("ambiguous"),
                "{ambiguous}: {error}"
            );
        }
        let union = schema_for_a(json!({"type": ["string", "integer"]}));
        assert!(parse_tool_calls(&one_arg("3"), std::slice::from_ref(&union)).is_err());
        assert_eq!(
            parse_tool_calls(&one_arg("Paris"), &[union]).unwrap()[0].arguments["a"],
            json!("Paris")
        );
        assert_eq!(
            parse_tool_calls(&one_arg("hello world"), &[untyped()]).unwrap()[0].arguments["a"],
            json!("hello world")
        );
        let object = schema_for_a(json!({"type": "object"}));
        let parsed = parse_tool_calls(
            &one_arg(r#"{"$serde_json::private::Number": "7"}"#),
            std::slice::from_ref(&object),
        )
        .unwrap();
        assert!(
            parsed[0].arguments["a"].is_object(),
            "the container is kept"
        );
        assert!(parse_tool_calls(&one_arg(r#"{"k": 1, "k": 2}"#), &[object]).is_err());
        let number = schema_for_a(json!({"type": "number"}));
        assert!(
            parse_tool_calls(&one_arg("1e999"), &[number]).is_err(),
            "unrenderable float"
        );
        let bad_ref = schema_for_a(json!({"$ref": "#/$defs/missing"}));
        assert!(
            parse_tool_calls(&one_arg("x"), &[bad_ref]).is_err(),
            "unresolvable $ref"
        );
    }

    /// A valid output finished at every char boundary with the token limit is
    /// complete or incomplete, never an error; tolerated whitespace and
    /// multibyte text included.
    #[test]
    fn every_prefix_of_valid_output_finishes_cleanly_at_the_token_limit() {
        for output in [
            "Caf\u{e9} \u{1f600} check.<tool_call>get_weather<arg_key>city</arg_key><arg_value>P\u{e9}ris</arg_value></tool_call>",
            "<tool_call> get_weather <arg_key>city</arg_key> <arg_value>Rome</arg_value> <arg_key>days</arg_key>\n<arg_value>2</arg_value> </tool_call>\n<tool_call>get_weather</tool_call>",
        ] {
            let (_, whole) = stream_all(&[output], vec![weather()], ToolOutputEnd::Stop);
            assert!(!whole.unwrap().calls.is_empty(), "{output}");
            for (end, _) in output.char_indices().skip(1) {
                let (_, finish) = stream_all(
                    &[&output[..end]],
                    vec![weather()],
                    ToolOutputEnd::TokenLimit,
                );
                assert!(
                    finish.is_ok(),
                    "prefix {:?}: {:?}",
                    &output[..end],
                    finish.err()
                );
            }
        }
    }

    fn stream_all(
        chunks: &[&str],
        definitions: Vec<ToolDefinition>,
        end: ToolOutputEnd,
    ) -> (String, Result<ToolOutputFinish>) {
        let mut stream = ToolOutputStream::new(definitions, 1 << 20);
        let mut visible = String::new();
        for chunk in chunks {
            match stream.push_visible(chunk) {
                Ok(text) => visible.push_str(&text),
                Err(error) => return (visible, Err(error)),
            }
        }
        let finish = stream.finish(end);
        if let Ok(finish) = &finish {
            visible.push_str(&finish.visible_tail);
        }
        (visible, finish)
    }

    /// Parsing a rendered call and rendering it back reproduces the bytes,
    /// for every argument type the template writes; values follow the
    /// schema.
    #[test]
    fn rendered_calls_parse_back_to_the_same_bytes() {
        let arguments = json!({
            "i": 7, "neg": -3, "x": 1.0, "big": 1e20, "small": 1.5e-07, "t": true,
            "n": null, "list": ["a", "\u{e9}", 2], "obj": {"k": 1, "nested": [true, null]},
            "numeric_string": "3", "unicode": "caf\u{e9} \u{1f600}", "multiline": "line1\nline2",
            "plain": "hello world"
        });
        let call = ToolCall {
            id: "c1".into(),
            name: "f".into(),
            arguments: arguments.as_object().unwrap().clone(),
        };
        let mut rendered = String::new();
        call.render(&mut rendered).unwrap();
        let parsed = parse_tool_calls(&rendered, &[typed()]).unwrap();
        assert_eq!(parsed.len(), 1);
        let back = ToolCall {
            id: "c1".into(),
            name: parsed[0].name.clone(),
            arguments: parsed[0].arguments.clone(),
        };
        let mut again = String::new();
        back.render(&mut again).unwrap();
        assert_eq!(again, rendered);
        // A string schema keeps numeric-looking text a string.
        assert_eq!(parsed[0].arguments["numeric_string"], json!("3"));
        assert_eq!(
            parsed[0].arguments["obj"],
            json!({"k": 1, "nested": [true, null]})
        );
        assert_eq!(parsed[0].arguments["plain"], json!("hello world"));
    }

    #[test]
    fn arguments_follow_the_declared_schema() {
        let block = "<tool_call>get_weather<arg_key>city</arg_key><arg_value>3</arg_value>\
            <arg_key>days</arg_key><arg_value>3</arg_value>\
            <arg_key>tags</arg_key><arg_value>[\"a\",\"b\"]</arg_value></tool_call>";
        let calls = parse_tool_calls(block, &[weather()]).unwrap();
        let args = &calls[0].arguments;
        assert_eq!(args["city"], json!("3"), "string-only schema keeps text");
        assert_eq!(args["days"], json!(3));
        assert_eq!(
            args["tags"],
            json!(["a", "b"]),
            "compact JSON decodes for a non-string schema"
        );
        for (bad, why) in [
            (
                "<tool_call>get_weather<arg_key>days</arg_key><arg_value>three</arg_value></tool_call>",
                "declared type",
            ),
            (
                "<tool_call>get_weather<arg_key>days</arg_key><arg_value>2.5</arg_value></tool_call>",
                "declared type",
            ),
            ("<tool_call>other</tool_call>", "no declared tool"),
            (
                "<tool_call>get_weather<arg_key>city</arg_key><arg_value>a</arg_value><arg_key>city</arg_key><arg_value>b</arg_value></tool_call>",
                "repeats",
            ),
            (
                "<tool_call>get_weather</tool_call>trailing",
                "not a tool call",
            ),
            ("<tool_call>get weather</tool_call>", "malformed"),
            (
                "<tool_call>get_weather<arg_key>a<b</arg_key><arg_value>1</arg_value></tool_call>",
                "malformed",
            ),
        ] {
            let error = parse_tool_calls(bad, &[weather()]).unwrap_err();
            assert_eq!(error.code(), "glm5_next_chat_tools");
            assert!(error.to_string().contains(why), "{bad}: {error}");
        }
    }

    /// Visible text, then two calls, split at every byte: the same visible
    /// text and calls; tool markers never leak as text.
    #[test]
    fn every_byte_split_streams_the_same_text_and_calls() {
        let output = "Let me check.<tool_call>get_weather<arg_key>city</arg_key><arg_value>Paris</arg_value></tool_call>\n<tool_call>get_weather<arg_key>city</arg_key><arg_value>Rome</arg_value><arg_key>days</arg_key><arg_value>2</arg_value></tool_call>";
        let (whole_text, whole) = stream_all(&[output], vec![weather()], ToolOutputEnd::Stop);
        let whole = whole.unwrap();
        assert_eq!(whole_text, "Let me check.");
        assert_eq!(whole.calls.len(), 2);
        assert_eq!(whole.calls[1].arguments["days"], json!(2));
        for split in 1..output.len() {
            if !output.is_char_boundary(split) {
                continue;
            }
            let (text, finish) = stream_all(
                &[&output[..split], &output[split..]],
                vec![weather()],
                ToolOutputEnd::Stop,
            );
            assert_eq!(text, whole_text, "split {split}");
            assert_eq!(finish.unwrap().calls, whole.calls, "split {split}");
        }
        // Byte by byte.
        let chars: Vec<String> = output.chars().map(String::from).collect();
        let pieces: Vec<&str> = chars.iter().map(String::as_str).collect();
        let (text, finish) = stream_all(&pieces, vec![weather()], ToolOutputEnd::Stop);
        assert_eq!(text, whole_text);
        assert_eq!(finish.unwrap().calls, whole.calls);
    }

    #[test]
    fn text_without_calls_and_marker_prefixes_are_released() {
        let (text, finish) = stream_all(
            &["Plain answer <tool", "s> and <tool_ca"],
            vec![weather()],
            ToolOutputEnd::Stop,
        );
        let finish = finish.unwrap();
        assert_eq!(text, "Plain answer <tools> and <tool_ca");
        assert!(finish.calls.is_empty() && !finish.incomplete_tool_block);
    }

    #[test]
    fn an_open_block_is_incomplete_at_the_token_limit_and_an_error_at_a_stop() {
        let open = ["Checking<tool_call>get_weather<arg_key>city</arg_key><arg_value>Par"];
        let (text, finish) = stream_all(&open, vec![weather()], ToolOutputEnd::TokenLimit);
        assert_eq!(text, "Checking");
        let finish = finish.unwrap();
        assert!(finish.incomplete_tool_block && finish.calls.is_empty());
        let (_, finish) = stream_all(&open, vec![weather()], ToolOutputEnd::Stop);
        assert_eq!(finish.unwrap_err().code(), "glm5_next_chat_tools");
        // A complete block at the token limit still publishes.
        let done = [
            "<tool_call>get_weather<arg_key>city</arg_key><arg_value>Paris</arg_value></tool_call>",
        ];
        let (_, finish) = stream_all(&done, vec![weather()], ToolOutputEnd::TokenLimit);
        assert_eq!(finish.unwrap().calls.len(), 1);
    }

    #[test]
    fn the_byte_budget_bounds_the_buffered_block() {
        let mut stream = ToolOutputStream::new(vec![weather()], 16);
        assert_eq!(stream.push_visible("ok ").unwrap(), "ok ");
        assert!(
            stream
                .push_visible("<tool_call>get_weather<arg_key>")
                .is_err()
        );
        assert!(
            stream.push_visible("x").is_err(),
            "failed streams stay failed"
        );
    }
}
