//! `qwen run` chat output for the verified-chat lanes (K2 Horizon,
//! GLM-5.3-Flash), in the format `--format` selects:
//!
//! - `text` (default): the decoded generated bytes in order, on stdout, as
//!   every family prints them. Reasoning and tool markers the model
//!   generates stay visible; no prompt opener is synthesized. A bounded
//!   observer (the family's tools-free chat grammar, events discarded as
//!   they arrive) validates the stream: a token limit inside reasoning
//!   succeeds, a stop before the reasoning closes fails after the bytes
//!   already printed. Tool syntax is literal text in this format.
//! - `responses`: one Open Responses object on stdout, assembled from the
//!   family's structured grammar (reasoning, message and `function_call`
//!   items) after generation succeeds; diagnostics stay on stderr.

use crate::serve::events::{StopReason, Usage};
use crate::serve::items::ServeRequest;
use crate::serve::output_partition::{GenerationEnd, OutputPartition, OutputProtocol};
use crate::serve::partition::PartitionEvent;
use anyhow::{Result, anyhow};
use std::io::Write;

/// `qwen run --format`.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, clap::ValueEnum)]
pub(crate) enum RunFormat {
    /// The decoded generated bytes, as every family prints them.
    #[default]
    Text,
    /// One Open Responses object (verified K2 and GLM chat).
    Responses,
}

impl RunFormat {
    pub(crate) fn label(self) -> &'static str {
        match self {
            Self::Text => "text",
            Self::Responses => "responses",
        }
    }
}

/// A chat lane's output in progress.
pub(crate) enum ChatOutput {
    Text {
        observer: OutputPartition,
        closed: bool,
        wrote: bool,
    },
    Responses {
        partition: OutputPartition,
        events: Vec<PartitionEvent>,
    },
}

/// How a chat generation ended.
pub(crate) struct ChatFinish {
    /// The generated reasoning closed (the answer began).
    pub(crate) reasoning_closed: bool,
}

impl ChatOutput {
    /// `chat`: the family's tools-free chat grammar (the text observer);
    /// `structured`: the grammar whose events build the Responses object
    /// (the chat grammar, or the tool grammar when functions are declared).
    pub(crate) fn new(format: RunFormat, chat: OutputProtocol, structured: OutputProtocol) -> Self {
        match format {
            RunFormat::Text => Self::Text {
                observer: OutputPartition::new(chat),
                closed: false,
                wrote: false,
            },
            RunFormat::Responses => Self::Responses {
                partition: OutputPartition::new(structured),
                events: Vec::new(),
            },
        }
    }

    /// One generated piece: printed now (text) or partitioned (responses).
    pub(crate) fn piece(&mut self, bytes: &[u8], stdout: &mut impl Write) -> Result<()> {
        match self {
            Self::Text {
                observer,
                closed,
                wrote,
            } => {
                stdout.write_all(bytes)?;
                stdout.flush()?;
                *wrote |= !bytes.is_empty();
                let mut events = Vec::new();
                observer.push(bytes, &mut events);
                *closed |= events.contains(&PartitionEvent::ReasoningClosed);
            }
            Self::Responses { partition, events } => partition.push(bytes, events),
        }
        Ok(())
    }

    /// Generation failed: leave stdout on a fresh line; the error stands.
    pub(crate) fn abandon(&self, stdout: &mut impl Write) {
        if let Self::Text { wrote: true, .. } = self {
            let _ = writeln!(stdout);
            let _ = stdout.flush();
        }
    }

    /// Generation ended. Text: end the line and validate the stream (an
    /// invalid stop fails after the printed bytes). Responses: assemble and
    /// print one object from `request` (the run's resolved request echoes)
    /// and `usage`.
    pub(crate) fn finish(
        self,
        stop: StopReason,
        end: GenerationEnd,
        usage: Usage,
        request: impl FnOnce() -> Result<ServeRequest>,
        response_id: &str,
        stdout: &mut impl Write,
    ) -> Result<ChatFinish> {
        match self {
            Self::Text {
                observer,
                mut closed,
                wrote,
            } => {
                if wrote {
                    writeln!(stdout)?;
                    stdout.flush()?;
                }
                let mut events = Vec::new();
                let result = observer.finish(end, &mut events);
                closed |= events.contains(&PartitionEvent::ReasoningClosed);
                result.map_err(|error| anyhow!(error.message))?;
                Ok(ChatFinish {
                    reasoning_closed: closed,
                })
            }
            Self::Responses {
                partition,
                mut events,
            } => {
                partition
                    .finish(end, &mut events)
                    .map_err(|error| anyhow!(error.message))?;
                let closed = events.contains(&PartitionEvent::ReasoningClosed);
                let now = std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH)?;
                let response = crate::serve::events::build_response_object(
                    &request()?,
                    format!("{response_id}_{}_{}", std::process::id(), now.as_nanos()),
                    now.as_secs(),
                    &events,
                    stop,
                    usage,
                    None,
                )?;
                serde_json::to_writer(&mut *stdout, &response)?;
                writeln!(stdout)?;
                stdout.flush()?;
                Ok(ChatFinish {
                    reasoning_closed: closed,
                })
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::serve::output_partition::OutputProtocol;
    use qwen_llm::k2_horizon_chat::Effort as K2Effort;
    use serde_json::{Value, json};

    const GLM_STOP: GenerationEnd = GenerationEnd::StopToken(154_827);
    const K2_STOP: GenerationEnd = GenerationEnd::StopToken(1);

    fn request() -> Result<ServeRequest> {
        Ok(ServeRequest {
            model: "m".into(),
            reasoning: Some(json!({"effort": "low"})),
            ..Default::default()
        })
    }

    /// Text output for `pieces` and how it finished.
    fn text(chat: OutputProtocol, pieces: &[&[u8]], end: GenerationEnd) -> (Vec<u8>, Result<bool>) {
        let mut output = ChatOutput::new(RunFormat::Text, chat.clone(), chat);
        let mut stdout = Vec::new();
        for piece in pieces {
            output.piece(piece, &mut stdout).unwrap();
        }
        let usage = Usage {
            input_tokens: 1,
            output_tokens: pieces.len(),
            cached_tokens: 0,
        };
        let finish = output
            .finish(StopReason::Eos, end, usage, request, "resp", &mut stdout)
            .map(|finish| finish.reasoning_closed);
        (stdout, finish)
    }

    fn splits(text: &str) -> Vec<Vec<&[u8]>> {
        let bytes = text.as_bytes();
        let mut all = vec![vec![bytes]];
        all.push(bytes.chunks(1).collect());
        for at in 1..bytes.len() {
            all.push(vec![&bytes[..at], &bytes[at..]]);
        }
        all
    }

    /// Text is the generated bytes in order, markers and tool syntax
    /// included, at every split (UTF-8 continuation bytes included), with
    /// one trailing newline; the observer sees the close wherever it lands.
    #[test]
    fn text_is_the_generated_bytes_at_every_split() {
        let cases = [
            (OutputProtocol::Glm5NextChat, "plän</think>Answér", true),
            (
                OutputProtocol::Glm5NextChat,
                "x</think>Calling.<tool_call>f<arg_key>a</arg_key><arg_value>1</arg_value></tool_call>",
                true,
            ),
            (
                OutputProtocol::K2Chat {
                    effort: K2Effort::High,
                },
                "<ifm|think>r</ifm|think>A",
                true,
            ),
            (
                OutputProtocol::K2Chat {
                    effort: K2Effort::Medium,
                },
                "r</ifm|think_fast>A",
                true,
            ),
            (
                OutputProtocol::K2Chat {
                    effort: K2Effort::Low,
                },
                "r</ifm|think_faster>A",
                true,
            ),
        ];
        for (chat, generated, closed) in cases {
            let end = if matches!(chat, OutputProtocol::Glm5NextChat) {
                GLM_STOP
            } else {
                K2_STOP
            };
            for pieces in splits(generated) {
                let (stdout, finish) = text(chat.clone(), &pieces, end);
                assert_eq!(stdout, format!("{generated}\n").into_bytes(), "{generated}");
                assert_eq!(finish.unwrap(), closed, "{generated} {pieces:?}");
            }
        }
    }

    /// A token limit inside reasoning (a truncated close included) succeeds
    /// with reasoning open; a stop before the close fails after the bytes
    /// were printed; empty output prints nothing.
    #[test]
    fn text_validates_the_stream_without_changing_it() {
        for generated in ["still thinking", "still thinking</thi"] {
            let (stdout, finish) = text(
                OutputProtocol::Glm5NextChat,
                &[generated.as_bytes()],
                GenerationEnd::TokenLimit,
            );
            assert_eq!(stdout, format!("{generated}\n").into_bytes());
            assert!(!finish.unwrap());
        }
        let (stdout, finish) = text(OutputProtocol::Glm5NextChat, &[b"still thinking"], GLM_STOP);
        assert_eq!(stdout, b"still thinking\n");
        assert!(
            finish.is_err(),
            "a stop before </think> is a protocol error"
        );
        let (stdout, finish) = text(
            OutputProtocol::K2Chat {
                effort: K2Effort::Low,
            },
            &[b"r"],
            K2_STOP,
        );
        assert_eq!(stdout, b"r\n");
        assert!(finish.is_err());
        let (stdout, finish) = text(OutputProtocol::Glm5NextChat, &[], GenerationEnd::TokenLimit);
        assert!(stdout.is_empty());
        assert!(!finish.unwrap());
    }

    fn responses(structured: OutputProtocol, generated: &str, end: GenerationEnd) -> Value {
        let mut output = ChatOutput::new(
            RunFormat::Responses,
            OutputProtocol::Glm5NextChat,
            structured,
        );
        let mut stdout = Vec::new();
        for piece in generated.as_bytes().chunks(3) {
            output.piece(piece, &mut stdout).unwrap();
        }
        assert!(stdout.is_empty(), "nothing prints before the object");
        let usage = Usage {
            input_tokens: 1,
            output_tokens: 1,
            cached_tokens: 0,
        };
        output
            .finish(StopReason::Eos, end, usage, request, "resp", &mut stdout)
            .unwrap();
        let text = String::from_utf8(stdout).unwrap();
        assert_eq!(text.matches('\n').count(), 1, "one object, one line");
        serde_json::from_str(&text).unwrap()
    }

    /// Responses is one object: reasoning and message items for chat,
    /// function_call items when tools are declared.
    #[test]
    fn responses_is_one_object_with_reasoning_message_and_calls() {
        let chat = responses(OutputProtocol::Glm5NextChat, "plan</think>Answer", GLM_STOP);
        let types: Vec<_> = chat["output"]
            .as_array()
            .unwrap()
            .iter()
            .map(|item| item["type"].as_str().unwrap())
            .collect();
        assert_eq!(types, ["reasoning", "message"]);
        assert_eq!(chat["output"][1]["content"][0]["text"], "Answer");
        let tool = qwen_llm::glm5_next_chat::ToolDefinition::from_value(&json!({
            "name": "f", "parameters": {"type": "object", "properties": {"a": {"type": "integer"}}}}))
        .unwrap();
        let structured = OutputProtocol::Glm5NextTools {
            definitions: vec![tool],
            max_bytes: 1 << 20,
        };
        let mut output = ChatOutput::new(
            RunFormat::Responses,
            OutputProtocol::Glm5NextChat,
            structured,
        );
        let mut stdout = Vec::new();
        let generated =
            b"x</think><tool_call>f<arg_key>a</arg_key><arg_value>7</arg_value></tool_call>";
        for piece in generated.chunks(5) {
            output.piece(piece, &mut stdout).unwrap();
        }
        let usage = Usage {
            input_tokens: 1,
            output_tokens: 1,
            cached_tokens: 0,
        };
        // The envelope publishes only calls to tools the request allows.
        let request = || {
            Ok(ServeRequest {
                model: "m".into(),
                allowed_tools: vec!["f".into()],
                parallel_tool_calls: true,
                ..Default::default()
            })
        };
        output
            .finish(
                StopReason::Eos,
                GenerationEnd::StopToken(154_829),
                usage,
                request,
                "resp",
                &mut stdout,
            )
            .unwrap();
        let calls: Value = serde_json::from_slice(&stdout).unwrap();
        let call = calls["output"]
            .as_array()
            .unwrap()
            .iter()
            .find(|item| item["type"] == "function_call")
            .unwrap();
        assert_eq!(call["name"], "f");
        assert_eq!(call["arguments"], r#"{"a":7}"#);
    }
}
