//! Incremental Muse ATEM output grammar over exact generated bytes.

use super::items::ServeError;
use super::output_partition::GenerationEnd;
use super::partition::PartitionEvent;
use super::tool_parse::ParsedCall;
use serde_json::{Map, Value};
use std::collections::BTreeSet;

const INITIAL_HEADER: &[u8] = b" to=";
const CONTINUATION_HEADER: &[u8] = b"<|start|>assistant to=";
const MESSAGE_MARKER: &[u8] = b"<|message|>";
const EOM: &[u8] = b"<|eom|>";
const CONTROL_OPEN: &[u8] = b"<|";
const MAX_RECIPIENT_BYTES: usize = 64;

#[derive(Debug, Default)]
struct StrictUtf8Assembler {
    pending: Vec<u8>,
}

impl StrictUtf8Assembler {
    fn push(&mut self, bytes: &[u8]) -> Result<String, String> {
        self.pending.extend_from_slice(bytes);
        match std::str::from_utf8(&self.pending) {
            Ok(text) => {
                let text = text.to_owned();
                self.pending.clear();
                Ok(text)
            }
            Err(error) if error.error_len().is_some() => {
                self.pending.clear();
                Err("generated Muse content contains invalid UTF-8".into())
            }
            Err(error) => {
                let valid = error.valid_up_to();
                let text = std::str::from_utf8(&self.pending[..valid])
                    .expect("validated UTF-8 prefix")
                    .to_owned();
                self.pending.drain(..valid);
                Ok(text)
            }
        }
    }

    fn finish_boundary(&mut self) -> Result<(), String> {
        if self.pending.is_empty() {
            Ok(())
        } else {
            self.pending.clear();
            Err("generated Muse content ends inside a UTF-8 sequence".into())
        }
    }

    fn discard_incomplete(&mut self) {
        self.pending.clear();
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum HeaderContext {
    Initial,
    AfterReasoning,
    AfterTool,
}

#[derive(Debug)]
enum Phase {
    Header(HeaderContext),
    Reasoning,
    Visible,
    Tool(String),
}

pub(crate) struct MuseAtemPartition {
    phase: Phase,
    pending: Vec<u8>,
    reasoning_utf8: StrictUtf8Assembler,
    visible_utf8: StrictUtf8Assembler,
    calls: Vec<ParsedCall>,
    declared_tools: BTreeSet<String>,
    failure: Option<String>,
    eos_token_id: i32,
    eot_token_id: i32,
}

impl MuseAtemPartition {
    pub(crate) fn new(eos_token_id: i32, eot_token_id: i32, declared_tools: Vec<String>) -> Self {
        Self {
            phase: Phase::Header(HeaderContext::Initial),
            pending: Vec::new(),
            reasoning_utf8: StrictUtf8Assembler::default(),
            visible_utf8: StrictUtf8Assembler::default(),
            calls: Vec::new(),
            declared_tools: declared_tools.into_iter().collect(),
            failure: None,
            eos_token_id,
            eot_token_id,
        }
    }

    pub(crate) fn push(&mut self, bytes: &[u8], events: &mut Vec<PartitionEvent>) {
        if self.failure.is_some() {
            return;
        }
        self.pending.extend_from_slice(bytes);
        while self.failure.is_none() && self.advance(events) {}
    }

    fn advance(&mut self, events: &mut Vec<PartitionEvent>) -> bool {
        match &self.phase {
            Phase::Header(context) => self.advance_header(*context, events),
            Phase::Reasoning => self.advance_reasoning(events),
            Phase::Visible => self.advance_visible(events),
            Phase::Tool(recipient) => self.advance_tool(recipient.clone()),
        }
    }

    fn advance_header(&mut self, context: HeaderContext, events: &mut Vec<PartitionEvent>) -> bool {
        let prefix = if context == HeaderContext::Initial {
            INITIAL_HEADER
        } else {
            CONTINUATION_HEADER
        };
        if self.pending.len() < prefix.len() {
            if prefix.starts_with(&self.pending) {
                return false;
            }
            self.fail("assistant header does not match the Muse ATEM prefix");
            return false;
        }
        if !self.pending.starts_with(prefix) {
            self.fail("assistant header does not match the Muse ATEM prefix");
            return false;
        }
        let rest = &self.pending[prefix.len()..];
        let Some(marker_index) = find_bytes(rest, MESSAGE_MARKER) else {
            if rest.len() > MAX_RECIPIENT_BYTES + MESSAGE_MARKER.len() {
                self.fail("assistant recipient header exceeds its bounded syntax");
            }
            return false;
        };
        let recipient_bytes = &rest[..marker_index];
        if recipient_bytes.len() > MAX_RECIPIENT_BYTES {
            self.fail("assistant recipient exceeds its bounded syntax");
            return false;
        }
        let Ok(recipient) = std::str::from_utf8(recipient_bytes) else {
            self.fail("assistant recipient is not UTF-8");
            return false;
        };
        if !valid_atem_path(recipient) {
            self.fail("assistant recipient is not a safe ATEM path");
            return false;
        }
        let recipient = recipient.to_owned();
        self.pending
            .drain(..prefix.len() + marker_index + MESSAGE_MARKER.len());
        match recipient.as_str() {
            "self" if context != HeaderContext::AfterTool => {
                self.phase = Phase::Reasoning;
            }
            "user" if context != HeaderContext::AfterTool => {
                if context == HeaderContext::AfterReasoning {
                    events.push(PartitionEvent::ReasoningClosed);
                }
                self.phase = Phase::Visible;
            }
            "self" | "user" => {
                self.fail("tool-call batches cannot continue into self or user content");
                return false;
            }
            _ => {
                if !self.declared_tools.contains(&recipient) {
                    self.fail(format!(
                        "assistant selected undeclared tool recipient {recipient:?}"
                    ));
                    return false;
                }
                if context == HeaderContext::AfterReasoning {
                    events.push(PartitionEvent::ReasoningClosed);
                }
                self.phase = Phase::Tool(recipient);
            }
        }
        true
    }

    fn advance_reasoning(&mut self, events: &mut Vec<PartitionEvent>) -> bool {
        if let Some(index) = find_bytes(&self.pending, CONTROL_OPEN) {
            let content = self.pending.drain(..index).collect::<Vec<_>>();
            self.emit_reasoning(&content, events);
            if self.failure.is_some() {
                return false;
            }
            let control = self.pending.as_slice();
            if control.len() < EOM.len() && EOM.starts_with(control) {
                return false;
            }
            if control.starts_with(EOM) {
                if let Err(error) = self.reasoning_utf8.finish_boundary() {
                    self.fail(error);
                    return false;
                }
                self.pending.drain(..EOM.len());
                self.phase = Phase::Header(HeaderContext::AfterReasoning);
                return true;
            }
            self.fail("reasoning contains an unexpected Muse control marker");
            return false;
        }
        let safe = safe_emit_len_bytes(&self.pending, CONTROL_OPEN);
        if safe == 0 {
            return false;
        }
        let content = self.pending.drain(..safe).collect::<Vec<_>>();
        self.emit_reasoning(&content, events);
        false
    }

    fn advance_visible(&mut self, events: &mut Vec<PartitionEvent>) -> bool {
        if let Some(index) = find_bytes(&self.pending, CONTROL_OPEN) {
            let content = self.pending.drain(..index).collect::<Vec<_>>();
            self.emit_visible(&content, events);
            if self.failure.is_some() {
                return false;
            }
            self.fail("visible Muse output contains an unexpected control marker");
            return false;
        }
        let safe = safe_emit_len_bytes(&self.pending, CONTROL_OPEN);
        if safe == 0 {
            return false;
        }
        let content = self.pending.drain(..safe).collect::<Vec<_>>();
        self.emit_visible(&content, events);
        false
    }

    fn advance_tool(&mut self, recipient: String) -> bool {
        let Some(index) = find_bytes(&self.pending, EOM) else {
            return false;
        };
        let segment = self.pending.drain(..index).collect::<Vec<_>>();
        self.pending.drain(..EOM.len());
        match parse_tool_segment(&recipient, &segment) {
            Ok(call) => self.calls.push(call),
            Err(error) => {
                self.fail(error);
                return false;
            }
        }
        self.phase = Phase::Header(HeaderContext::AfterTool);
        true
    }

    fn emit_reasoning(&mut self, bytes: &[u8], events: &mut Vec<PartitionEvent>) {
        match self.reasoning_utf8.push(bytes) {
            Ok(text) if !text.is_empty() => events.push(PartitionEvent::Reasoning(text)),
            Ok(_) => {}
            Err(error) => self.fail(error),
        }
    }

    fn emit_visible(&mut self, bytes: &[u8], events: &mut Vec<PartitionEvent>) {
        match self.visible_utf8.push(bytes) {
            Ok(text) if !text.is_empty() => events.push(PartitionEvent::Visible(text)),
            Ok(_) => {}
            Err(error) => self.fail(error),
        }
    }

    fn fail(&mut self, detail: impl Into<String>) {
        self.failure = Some(detail.into());
    }

    pub(crate) fn finish(
        mut self,
        end: GenerationEnd,
        events: &mut Vec<PartitionEvent>,
    ) -> Result<(), ServeError> {
        if let Some(detail) = self.failure.take() {
            return Err(protocol_error(detail));
        }
        if let GenerationEnd::StopToken(token) = end
            && token != self.eos_token_id
            && token != self.eot_token_id
        {
            return Err(protocol_error(format!(
                "generation stopped on unexpected token {token}"
            )));
        }
        let phase = std::mem::replace(&mut self.phase, Phase::Header(HeaderContext::Initial));
        match phase {
            Phase::Header(HeaderContext::Initial) => {
                if !end.is_token_limit() {
                    return Err(protocol_error("generation ended inside the initial header"));
                }
            }
            Phase::Header(HeaderContext::AfterReasoning) => {
                if !end.is_token_limit() {
                    return Err(protocol_error(
                        "generation ended between reasoning and its next assistant segment",
                    ));
                }
                events.push(PartitionEvent::ReasoningClosed);
            }
            Phase::Header(HeaderContext::AfterTool) => {
                if !end.is_token_limit() {
                    return Err(protocol_error(
                        "generation ended between tool-call assistant segments",
                    ));
                }
                self.calls.clear();
            }
            Phase::Reasoning => {
                if !end.is_token_limit() {
                    return Err(protocol_error(
                        "generation stopped before reasoning emitted <|eom|>",
                    ));
                }
                let safe = find_bytes(&self.pending, CONTROL_OPEN)
                    .unwrap_or_else(|| safe_emit_len_bytes(&self.pending, CONTROL_OPEN));
                let pending = self.pending.drain(..safe).collect::<Vec<_>>();
                self.emit_reasoning(&pending, events);
                if let Some(detail) = self.failure.take() {
                    return Err(protocol_error(detail));
                }
                self.reasoning_utf8.discard_incomplete();
            }
            Phase::Visible => {
                if find_bytes(&self.pending, CONTROL_OPEN).is_some() {
                    return Err(protocol_error(
                        "visible Muse output ended with an unexpected control marker",
                    ));
                }
                let safe = if end.is_token_limit() {
                    safe_emit_len_bytes(&self.pending, CONTROL_OPEN)
                } else {
                    self.pending.len()
                };
                let pending = self.pending.drain(..safe).collect::<Vec<_>>();
                self.emit_visible(&pending, events);
                if let Some(detail) = self.failure.take() {
                    return Err(protocol_error(detail));
                }
                if end.is_token_limit() {
                    self.visible_utf8.discard_incomplete();
                } else if let Err(error) = self.visible_utf8.finish_boundary() {
                    return Err(protocol_error(error));
                }
            }
            Phase::Tool(recipient) => {
                if end.is_token_limit() {
                    self.calls.clear();
                    return Ok(());
                }
                let call = parse_tool_segment(&recipient, &self.pending).map_err(protocol_error)?;
                self.calls.push(call);
                events.extend(self.calls.into_iter().map(PartitionEvent::FunctionCall));
            }
        }
        Ok(())
    }

    pub(crate) fn abort(self, _events: &mut Vec<PartitionEvent>) {
        // Already-emitted reasoning/visible content is safe. Pending bytes can
        // be a split control marker or uncommitted call batch and are dropped.
    }
}

fn protocol_error(detail: impl Into<String>) -> ServeError {
    ServeError::server_error(format!("invalid Muse ATEM model output: {}", detail.into()))
}

fn parse_tool_segment(recipient: &str, bytes: &[u8]) -> Result<ParsedCall, String> {
    let segment =
        std::str::from_utf8(bytes).map_err(|_| "tool-call segment is not UTF-8".to_owned())?;
    let mut rest = segment
        .strip_prefix("<atem:function_calls>\n<atem:invoke name=\"")
        .ok_or_else(|| "tool-call segment has no canonical ATEM opener".to_owned())?;
    let name_end = rest
        .find("\">\n")
        .ok_or_else(|| "tool-call invoke name is unterminated".to_owned())?;
    let name = &rest[..name_end];
    if name != recipient || !valid_atem_path(name) {
        return Err("tool recipient and invoke name differ or are unsafe".into());
    }
    rest = &rest[name_end + 3..];
    let mut arguments = Map::new();
    while let Some(after_open) = rest.strip_prefix("<atem:parameter name=\"") {
        let key_end = after_open
            .find("\">")
            .ok_or_else(|| "tool parameter name is unterminated".to_owned())?;
        let key = &after_open[..key_end];
        if !valid_atem_segment(key) || arguments.contains_key(key) {
            return Err("tool parameter name is unsafe or duplicated".into());
        }
        let value_region = &after_open[key_end + 2..];
        let value_end = value_region
            .find("</atem:parameter>\n")
            .ok_or_else(|| "tool parameter value is unterminated".to_owned())?;
        let raw = &value_region[..value_end];
        let value = decode_parameter_value(raw);
        validate_replay_value(&value)?;
        arguments.insert(key.to_owned(), value);
        rest = &value_region[value_end + "</atem:parameter>\n".len()..];
    }
    if rest != "</atem:invoke>\n</atem:function_calls>" {
        return Err("tool-call segment has malformed closing syntax or a suffix".into());
    }
    Ok(ParsedCall {
        name: name.to_owned(),
        arguments,
    })
}

fn decode_parameter_value(raw: &str) -> Value {
    match serde_json::from_str::<Value>(raw) {
        Ok(value @ (Value::Object(_) | Value::Array(_) | Value::Number(_) | Value::Bool(_))) => {
            value
        }
        Ok(Value::Null) => Value::Null,
        _ => Value::String(raw.to_owned()),
    }
}

fn valid_atem_path(value: &str) -> bool {
    !value.is_empty() && value.split('.').all(valid_atem_segment)
}

fn valid_atem_segment(value: &str) -> bool {
    !value.is_empty()
        && value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-'))
}

fn validate_replay_value(value: &Value) -> Result<(), String> {
    match value {
        Value::String(value) => validate_replay_string(value),
        Value::Array(values) => values.iter().try_for_each(validate_replay_value),
        Value::Object(values) => {
            for (key, value) in values {
                validate_replay_string(key)?;
                validate_replay_value(value)?;
            }
            Ok(())
        }
        Value::Null | Value::Bool(_) | Value::Number(_) => Ok(()),
    }
}

fn validate_replay_string(value: &str) -> Result<(), String> {
    for marker in ["<|", "<atem:", "</atem:"] {
        if value.contains(marker) {
            return Err(format!(
                "tool parameter contains reserved Muse delimiter {marker:?}"
            ));
        }
    }
    Ok(())
}

fn find_bytes(haystack: &[u8], needle: &[u8]) -> Option<usize> {
    haystack
        .windows(needle.len())
        .position(|window| window == needle)
}

fn safe_emit_len_bytes(pending: &[u8], marker: &[u8]) -> usize {
    let max_hold = marker.len().saturating_sub(1).min(pending.len());
    for hold in (1..=max_hold).rev() {
        if marker.starts_with(&pending[pending.len() - hold..]) {
            return pending.len() - hold;
        }
    }
    pending.len()
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    const EOS: i32 = 1;
    const EOT: i32 = 2;

    fn new_partition() -> MuseAtemPartition {
        MuseAtemPartition::new(EOS, EOT, vec!["weather_lookup".into()])
    }

    fn run_bytewise(full: &[u8], end: GenerationEnd) -> Result<Vec<PartitionEvent>, ServeError> {
        let mut partition = new_partition();
        let mut events = Vec::new();
        for byte in full {
            partition.push(&[*byte], &mut events);
        }
        partition.finish(end, &mut events)?;
        Ok(events)
    }

    #[derive(Debug, PartialEq)]
    struct EventSummary {
        reasoning: String,
        visible: String,
        reasoning_closed: usize,
        calls: Vec<ParsedCall>,
    }

    fn summarize(events: Vec<PartitionEvent>) -> EventSummary {
        let mut summary = EventSummary {
            reasoning: String::new(),
            visible: String::new(),
            reasoning_closed: 0,
            calls: Vec::new(),
        };
        for event in events {
            match event {
                PartitionEvent::Reasoning(text) => summary.reasoning.push_str(&text),
                PartitionEvent::Visible(text) => summary.visible.push_str(&text),
                PartitionEvent::ReasoningClosed => summary.reasoning_closed += 1,
                PartitionEvent::FunctionCall(call) => summary.calls.push(call),
            }
        }
        summary
    }

    #[test]
    fn direct_visible_and_reasoning_visible_are_chunk_invariant() {
        let direct = " to=user<|message|>héllo 数学";
        let events = run_bytewise(direct.as_bytes(), GenerationEnd::StopToken(EOT)).unwrap();
        assert_eq!(
            events
                .iter()
                .filter_map(|event| match event {
                    PartitionEvent::Visible(text) => Some(text.as_str()),
                    _ => None,
                })
                .collect::<String>(),
            "héllo 数学"
        );

        let reasoned = concat!(
            " to=self<|message|>plan carefully<|eom|>",
            "<|start|>assistant to=user<|message|>answer"
        );
        let events = run_bytewise(reasoned.as_bytes(), GenerationEnd::StopToken(EOS)).unwrap();
        let reasoning = events
            .iter()
            .filter_map(|event| match event {
                PartitionEvent::Reasoning(text) => Some(text.as_str()),
                _ => None,
            })
            .collect::<String>();
        let visible = events
            .iter()
            .filter_map(|event| match event {
                PartitionEvent::Visible(text) => Some(text.as_str()),
                _ => None,
            })
            .collect::<String>();
        assert_eq!(reasoning, "plan carefully");
        assert_eq!(visible, "answer");
        assert_eq!(
            events
                .iter()
                .filter(|event| matches!(event, PartitionEvent::ReasoningClosed))
                .count(),
            1
        );
    }

    #[test]
    fn complete_tool_batch_commits_only_at_terminal_stop() {
        let call = concat!(
            " to=weather_lookup<|message|><atem:function_calls>\n",
            "<atem:invoke name=\"weather_lookup\">\n",
            "<atem:parameter name=\"city\">Paris</atem:parameter>\n",
            "<atem:parameter name=\"days\">2</atem:parameter>\n",
            "</atem:invoke>\n</atem:function_calls>"
        );
        let events = run_bytewise(call.as_bytes(), GenerationEnd::StopToken(EOT)).unwrap();
        assert_eq!(events.len(), 1);
        let PartitionEvent::FunctionCall(parsed) = &events[0] else {
            panic!("expected parsed call")
        };
        assert_eq!(parsed.name, "weather_lookup");
        assert_eq!(parsed.arguments["city"], json!("Paris"));
        assert_eq!(parsed.arguments["days"], json!(2));

        let truncated = run_bytewise(call.as_bytes(), GenerationEnd::TokenLimit).unwrap();
        assert!(truncated.is_empty(), "truncated call must not commit");
    }

    #[test]
    fn truncation_never_leaks_control_syntax() {
        for prefix in [
            " to=",
            " to=self<|message|>partial reasoning<|eo",
            " to=weather_lookup<|message|><atem:function_calls>",
        ] {
            let events = run_bytewise(prefix.as_bytes(), GenerationEnd::TokenLimit).unwrap();
            assert!(events.iter().all(|event| match event {
                PartitionEvent::Reasoning(text) | PartitionEvent::Visible(text) => {
                    !text.contains("<|") && !text.contains("<atem:")
                }
                PartitionEvent::ReasoningClosed => true,
                PartitionEvent::FunctionCall(_) => false,
            }));
        }
    }

    #[test]
    fn malformed_completed_protocol_fails_without_salvaging_calls() {
        for malformed in [
            "raw answer",
            " to=other<|message|><atem:function_calls>\n<atem:invoke name=\"different\">\n</atem:invoke>\n</atem:function_calls>",
            " to=user<|message|>answer<|eom|>",
        ] {
            assert!(
                run_bytewise(malformed.as_bytes(), GenerationEnd::StopToken(EOT)).is_err(),
                "accepted malformed emission {malformed:?}"
            );
        }
    }

    #[test]
    fn every_two_chunk_boundary_preserves_direct_reasoning_and_call_semantics() {
        for (full, end) in [
            (
                " to=user<|message|>héllo 数学",
                GenerationEnd::StopToken(EOT),
            ),
            (
                concat!(
                    " to=self<|message|>plan<|eom|>",
                    "<|start|>assistant to=user<|message|>answer"
                ),
                GenerationEnd::StopToken(EOS),
            ),
            (
                concat!(
                    " to=weather_lookup<|message|><atem:function_calls>\n",
                    "<atem:invoke name=\"weather_lookup\">\n",
                    "<atem:parameter name=\"city\">Paris</atem:parameter>\n",
                    "</atem:invoke>\n</atem:function_calls>"
                ),
                GenerationEnd::StopToken(EOT),
            ),
        ] {
            let expected = summarize(run_bytewise(full.as_bytes(), end).unwrap());
            for split in 0..=full.len() {
                let mut partition = new_partition();
                let mut events = Vec::new();
                partition.push(&full.as_bytes()[..split], &mut events);
                partition.push(&full.as_bytes()[split..], &mut events);
                partition.finish(end, &mut events).unwrap();
                assert_eq!(summarize(events), expected, "split at byte {split}");
            }
        }
    }

    #[test]
    fn controls_and_invalid_utf8_fail_without_crossing_content_boundaries() {
        for malformed in [
            b" to=self<|message|>plan<|eot|>".as_slice(),
            b" to=user<|message|>answer<|start|>".as_slice(),
            b" to=self<|message|>plan\xe2<|eom|>".as_slice(),
            b" to=user<|message|>answer\xff".as_slice(),
        ] {
            assert!(
                run_bytewise(malformed, GenerationEnd::StopToken(EOT)).is_err(),
                "accepted malformed bytes {malformed:?}"
            );
        }

        let mut truncated = b" to=user<|message|>safe".to_vec();
        truncated.push(0xe2);
        let events = run_bytewise(&truncated, GenerationEnd::TokenLimit).unwrap();
        assert_eq!(summarize(events).visible, "safe");
    }

    #[test]
    fn tool_calls_require_declarations_and_replay_safe_values() {
        let undeclared = concat!(
            " to=secret<|message|><atem:function_calls>\n",
            "<atem:invoke name=\"secret\">\n</atem:invoke>\n",
            "</atem:function_calls>"
        );
        assert!(run_bytewise(undeclared.as_bytes(), GenerationEnd::StopToken(EOT)).is_err());

        let escaped_delimiter = concat!(
            " to=weather_lookup<|message|><atem:function_calls>\n",
            "<atem:invoke name=\"weather_lookup\">\n",
            "<atem:parameter name=\"payload\">{\"nested\":\"\\u003catem:invoke>\"}</atem:parameter>\n",
            "</atem:invoke>\n</atem:function_calls>"
        );
        assert!(run_bytewise(escaped_delimiter.as_bytes(), GenerationEnd::StopToken(EOT)).is_err());

        let key = "k".repeat(96);
        let long_key = format!(
            " to=weather_lookup<|message|><atem:function_calls>\n<atem:invoke name=\"weather_lookup\">\n<atem:parameter name=\"{key}\">ok</atem:parameter>\n</atem:invoke>\n</atem:function_calls>"
        );
        let events = run_bytewise(long_key.as_bytes(), GenerationEnd::StopToken(EOT)).unwrap();
        let summary = summarize(events);
        assert_eq!(summary.calls[0].arguments[&key], json!("ok"));
    }

    #[test]
    fn later_protocol_failure_keeps_the_closed_reasoning_boundary() {
        let malformed = concat!(
            " to=self<|message|>done<|eom|>",
            "<|start|>assistant to=user<|message|>safe<|bad|>"
        );
        let mut partition = new_partition();
        let mut events = Vec::new();
        partition.push(malformed.as_bytes(), &mut events);
        assert!(
            partition
                .finish(GenerationEnd::StopToken(EOT), &mut events)
                .is_err()
        );
        let summary = summarize(events);
        assert_eq!(summary.reasoning, "done");
        assert_eq!(summary.reasoning_closed, 1);
        assert_eq!(summary.visible, "safe");
    }
}
