//! DeepSeek V4 prompt rendering for serve items.
//!
//! Delegates to the byte-pinned release encoder
//! (`messages::render_deepseek_v4_0731_messages_prompt`) rather than
//! re-implementing the 0731 contract. Two serve-specific decisions:
//!
//! - **Reasoning is always preserved when a thinking tier is active.**
//!   Checkpoint reuse needs history to be a token-exact extension of the
//!   completed-turn snapshot, and the release encoder only emits faithful
//!   history under `preserve_reasoning` (PERF-LOG 2026-08-13).
//! - **Thinking tiers pre-open `<think>`**, so generated bytes are
//!   headless (`reasoning</think>visible`). [`preopens_reasoning`] tells
//!   the transport which partition mode to use.
//! - **Tools** render through the same pinned encoder: declarations on the
//!   system message, DSML tool calls on assistant turns, tool results
//!   merged into user turns. Declared tools also disable reasoning dropping
//!   in the encoder, which coincides with the serve preserve policy.

use super::items::{ServeError, ServeRequest};
use crate::messages::{
    ChatMessage, DeepSeekV4EncodeOptions, DeepSeekV4Reasoning,
    render_deepseek_v4_0731_messages_prompt,
};
use crate::model_request::Turn;

/// Map the spec's `reasoning.effort` onto DeepSeek V4 release tiers.
/// Absent effort is ordinary chat (no thinking), matching the CLI default.
/// Unknown values fail closed rather than inventing a tier.
pub(crate) fn reasoning_tier(request: &ServeRequest) -> Result<DeepSeekV4Reasoning, ServeError> {
    DeepSeekV4Reasoning::parse(request.reasoning_effort.as_deref())
        .map_err(|error| ServeError::invalid_request(Some("reasoning.effort"), error.message))
}

pub(crate) fn encode_options(
    request: &ServeRequest,
) -> Result<DeepSeekV4EncodeOptions, ServeError> {
    let reasoning = reasoning_tier(request)?;
    Ok(DeepSeekV4EncodeOptions {
        reasoning,
        // Faithful history is what makes completed-turn checkpoints reusable.
        preserve_reasoning: reasoning != DeepSeekV4Reasoning::None,
    })
}

/// True when the rendered prompt ends with an open `<think>`, so the
/// decode stream must be partitioned headless.
pub(crate) fn preopens_reasoning(request: &ServeRequest) -> Result<bool, ServeError> {
    Ok(reasoning_tier(request)? != DeepSeekV4Reasoning::None)
}

pub(crate) fn render_deepseek_v4_serve_prompt(
    request: &ServeRequest,
) -> Result<String, ServeError> {
    if request.no_thinking {
        return Err(ServeError::invalid_request(
            Some("x_qwen.no_thinking"),
            "DeepSeek V4 uses reasoning.effort; x_qwen.no_thinking is unsupported",
        ));
    }
    if request.thinking_requested {
        return Err(ServeError::invalid_request(
            Some("x_qwen.thinking"),
            "DeepSeek V4 selects thinking through reasoning.effort; x_qwen.thinking is unsupported",
        ));
    }
    if request.strip_history_thinking {
        return Err(ServeError::invalid_request(
            Some("x_qwen.history_thinking"),
            "DeepSeek V4 serve preserves reasoning history; strip is unsupported",
        ));
    }
    let options = encode_options(request)?;
    let mut messages = Vec::with_capacity(request.model_request.turns.len() + 1);
    if let Some(system) = request.model_request.system.as_deref() {
        messages.push(ChatMessage {
            role: "system".into(),
            content: system.to_owned(),
            ..Default::default()
        });
    }
    for turn in &request.model_request.turns {
        match turn {
            Turn::User(text) => messages.push(ChatMessage {
                role: "user".into(),
                content: text.clone(),
                ..Default::default()
            }),
            Turn::Assistant {
                reasoning,
                visible,
                calls,
            } => {
                messages.push(ChatMessage {
                    role: "assistant".into(),
                    content: visible.clone(),
                    reasoning: reasoning.clone(),
                    tool_calls: calls.clone(),
                    ..Default::default()
                });
            }
            Turn::ToolResults(results) => {
                for result in results {
                    messages.push(ChatMessage {
                        role: "tool".into(),
                        content: result.output.clone(),
                        ..Default::default()
                    });
                }
            }
        }
    }
    render_deepseek_v4_0731_messages_prompt(&messages, &request.model_request.tools, options)
        .map_err(|error| ServeError::invalid_request(Some("input"), error.to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::serve::items::parse_request;
    use crate::serve::render::{split_preopened_reasoning, split_reasoning};
    use serde_json::json;

    fn request(body: serde_json::Value) -> ServeRequest {
        parse_request(&body).expect("request parses")
    }

    /// Missing reasoning is empty reasoning (serve's rule for every family):
    /// thinking tiers render `<think></think>` for both, chat mode drops both.
    #[test]
    fn missing_history_reasoning_renders_as_explicit_empty_reasoning() {
        let user = |text: &str| json!({"role": "user", "content": text});
        let empty = json!({"type": "reasoning", "content": ""});
        let call =
            json!({"type": "function_call", "call_id": "c1", "name": "ping", "arguments": "{}"});
        let output = json!({"type": "function_call_output", "call_id": "c1", "output": "pong"});
        let answer = json!({"role": "assistant", "content": "Done."});
        let histories = [
            (
                json!([user("One"), answer, user("Two")]),
                json!([user("One"), empty, answer, user("Two")]),
            ),
            (
                json!([user("One"), call, output, answer, user("Two")]),
                json!([user("One"), empty, call, output, empty, answer, user("Two")]),
            ),
        ];
        for effort in [None, Some("high"), Some("max")] {
            for (missing, explicit) in &histories {
                let render = |input: &serde_json::Value| {
                    let mut body = json!({"model": "ds", "input": input,
                        "tools": [{"type": "function", "name": "ping", "parameters": {"type": "object"}}]});
                    if let Some(effort) = effort {
                        body["reasoning"] = json!({"effort": effort});
                    }
                    render_deepseek_v4_serve_prompt(&request(body)).unwrap()
                };
                assert_eq!(render(missing), render(explicit), "{effort:?} {missing}");
            }
        }
    }

    #[test]
    fn chat_mode_closes_thinking_and_is_not_preopened() {
        let request = request(json!({"model": "ds", "input": "hi"}));
        assert!(!preopens_reasoning(&request).unwrap());
        let prompt = render_deepseek_v4_serve_prompt(&request).unwrap();
        assert!(
            prompt.ends_with("</think>"),
            "chat mode preclosed: {prompt:?}"
        );
        // Ordinary chat output carries no tags: the existing splitter is right.
        let split = split_reasoning("plain answer");
        assert_eq!(split.reasoning, None);
        assert_eq!(split.visible, "plain answer");
    }

    #[test]
    fn thinking_tier_preopens_and_headless_split_recovers_reasoning() {
        let request = request(json!({
            "model": "ds", "input": "hi", "reasoning": {"effort": "high"},
        }));
        assert!(preopens_reasoning(&request).unwrap());
        let prompt = render_deepseek_v4_serve_prompt(&request).unwrap();
        assert!(
            prompt.ends_with("<think>"),
            "thinking mode pre-opens: {prompt:?}"
        );

        // The model emits headless reasoning; the naive splitter would call
        // all of it visible, which is exactly the S3 hazard.
        let emitted = "weigh the options\n</think>\n\nThe answer is 5.";
        let naive = split_reasoning(emitted);
        assert_eq!(naive.reasoning, None, "naive split misclassifies (hazard)");
        let headless = split_preopened_reasoning(emitted);
        assert_eq!(headless.reasoning, Some("weigh the options\n"));
        assert_eq!(headless.visible, "\n\nThe answer is 5.");
        assert!(headless.closed);
    }

    #[test]
    fn preserved_history_round_trips_verbatim_for_checkpoint_identity() {
        // Turn 1 emission, headless.
        let emitted = "step one\n</think>\n\nFive.";
        let split = split_preopened_reasoning(emitted);
        let turn2 = request(json!({
            "model": "ds",
            "reasoning": {"effort": "high"},
            "input": [
                {"role": "user", "content": "Add 2 and 3."},
                {"type": "reasoning", "content": split.reasoning.unwrap()},
                {"role": "assistant", "content": split.visible},
                {"role": "user", "content": "Now add 10."},
            ],
        }));
        let prompt = render_deepseek_v4_serve_prompt(&turn2).unwrap();
        // History must contain the exact generated bytes so the completed
        // checkpoint's token prefix extends cleanly.
        assert!(
            prompt.contains(emitted),
            "history lost byte identity: {prompt:?}"
        );
        assert!(prompt.ends_with("<think>"));
    }

    #[test]
    fn unknown_effort_and_history_controls_fail_closed() {
        let bad = request(json!({
            "model": "ds", "input": "hi", "reasoning": {"effort": "medium"},
        }));
        let error = render_deepseek_v4_serve_prompt(&bad).unwrap_err();
        assert_eq!(error.param.as_deref(), Some("reasoning.effort"));

        for x_qwen in [
            json!({"no_thinking": true}),
            json!({"history_thinking": "strip"}),
        ] {
            let unsupported = request(json!({"model":"ds", "input":"hi", "x_qwen":x_qwen}));
            assert!(render_deepseek_v4_serve_prompt(&unsupported).is_err());
        }
    }

    /// The Open Responses tool loop renders the pinned `tools_chat_one_round`
    /// fixture bytes: declarations on the system message, the DSML call
    /// block on the assistant turn, results merged into one user turn, and
    /// a chat-mode transition after the results.
    #[test]
    fn tool_loop_renders_the_pinned_fixture_bytes() {
        let fixture: serde_json::Value = serde_json::from_str(include_str!(
            "../../tests/fixtures/deepseek_v4_0731_chat_fixtures_v1.json"
        ))
        .unwrap();
        let case = fixture["cases"]
            .as_array()
            .unwrap()
            .iter()
            .find(|case| case["name"] == "tools_chat_one_round")
            .unwrap();
        let messages = case["messages"].as_array().unwrap();
        let assistant = &messages[2];
        let mut input = vec![json!({"role": "user", "content": messages[1]["content"]})];
        // The fixture's assistant turn carries reasoning; chat mode drops it,
        // so a reasoning item is a no-op here and is omitted.
        for call in assistant["tool_calls"].as_array().unwrap() {
            input.push(json!({
                "type": "function_call",
                "call_id": call["id"],
                "name": call["function"]["name"],
                "arguments": call["function"]["arguments"],
            }));
        }
        for result in &messages[3..] {
            input.push(json!({
                "type": "function_call_output",
                "call_id": result["tool_call_id"],
                "output": result["content"],
            }));
        }
        let request = request(json!({
            "model": "ds",
            "instructions": messages[0]["content"],
            "tools": case["tools"].as_array().unwrap().iter().map(|tool| json!({
                "type": "function",
                "name": tool["function"]["name"],
                "description": tool["function"]["description"],
                "parameters": tool["function"]["parameters"],
            })).collect::<Vec<_>>(),
            "input": input,
        }));
        let prompt = render_deepseek_v4_serve_prompt(&request).unwrap();
        assert_eq!(prompt, case["prompt"].as_str().unwrap());
    }
}
