//! DeepSeek V4 prompt rendering for serve items.
//!
//! Delegates to the byte-pinned release encoder
//! (`messages::render_deepseek_v4_0731_messages_prompt`) rather than
//! re-implementing the 0731 contract. Two serve-specific decisions:
//!
//! - **Reasoning is always preserved when a thinking tier is active.**
//!   Checkpoint reuse needs history to be a token-exact extension of the
//!   completed-turn snapshot, and the release encoder only emits faithful
//!   history under `preserve_reasoning` (PERF-LOG 2026-08-13).
//! - **Thinking tiers pre-open `<think>`**, so generated bytes are
//!   headless (`reasoning</think>visible`). [`preopens_reasoning`] tells
//!   the transport which partition mode to use.

use super::items::{ServeError, ServeRequest, Turn};
use crate::messages::{
    ChatMessage, DeepSeekV4EncodeOptions, DeepSeekV4Reasoning,
    render_deepseek_v4_0731_messages_prompt,
};

/// Map the spec's `reasoning.effort` onto DeepSeek V4 release tiers.
/// Absent effort is ordinary chat (no thinking), matching the CLI default.
/// Unknown values fail closed rather than inventing a tier.
pub(crate) fn reasoning_tier(request: &ServeRequest) -> Result<DeepSeekV4Reasoning, ServeError> {
    match request.reasoning_effort.as_deref() {
        None | Some("none") => Ok(DeepSeekV4Reasoning::None),
        Some("low") => Ok(DeepSeekV4Reasoning::Low),
        Some("high") => Ok(DeepSeekV4Reasoning::High),
        Some("max") => Ok(DeepSeekV4Reasoning::Max),
        Some(other) => Err(ServeError::invalid_request(
            Some("reasoning.effort"),
            format!("DeepSeek V4 supports reasoning.effort none|low|high|max; got {other:?}"),
        )),
    }
}

pub(crate) fn encode_options(
    request: &ServeRequest,
) -> Result<DeepSeekV4EncodeOptions, ServeError> {
    let reasoning = reasoning_tier(request)?;
    Ok(DeepSeekV4EncodeOptions {
        reasoning,
        // Faithful history is what makes completed-turn checkpoints reusable.
        preserve_reasoning: reasoning != DeepSeekV4Reasoning::None,
    })
}

/// True when the rendered prompt ends with an open `<think>`, so the
/// decode stream must be partitioned headless.
pub(crate) fn preopens_reasoning(request: &ServeRequest) -> Result<bool, ServeError> {
    Ok(reasoning_tier(request)? != DeepSeekV4Reasoning::None)
}

pub(crate) fn render_deepseek_v4_serve_prompt(
    request: &ServeRequest,
) -> Result<String, ServeError> {
    if request.no_thinking {
        return Err(ServeError::invalid_request(
            Some("x_qwen.no_thinking"),
            "DeepSeek V4 uses reasoning.effort; x_qwen.no_thinking is unsupported",
        ));
    }
    if request.strip_history_thinking {
        return Err(ServeError::invalid_request(
            Some("x_qwen.history_thinking"),
            "DeepSeek V4 serve preserves reasoning history; strip is unsupported",
        ));
    }
    let options = encode_options(request)?;
    if !request.tools.is_empty() {
        // Fail closed rather than dropping definitions the model never sees
        // (k3 R1.7); DS4 tool support is not implemented.
        return Err(ServeError::invalid_request(
            Some("tools"),
            "DeepSeek V4 serve does not support tools yet",
        ));
    }
    let mut messages = Vec::with_capacity(request.turns.len() + 1);
    if let Some(system) = request.system.as_deref() {
        messages.push(ChatMessage {
            role: "system".into(),
            content: system.to_owned(),
            ..Default::default()
        });
    }
    for turn in &request.turns {
        match turn {
            Turn::User(text) => messages.push(ChatMessage {
                role: "user".into(),
                content: text.clone(),
                ..Default::default()
            }),
            Turn::Assistant {
                reasoning,
                visible,
                calls,
            } => {
                if !calls.is_empty() {
                    return Err(ServeError::invalid_request(
                        Some("input"),
                        "DeepSeek V4 serve does not support tool calls yet",
                    ));
                }
                messages.push(ChatMessage {
                    role: "assistant".into(),
                    content: visible.clone(),
                    reasoning: reasoning.clone(),
                    ..Default::default()
                });
            }
            Turn::ToolResults(_) => {
                return Err(ServeError::invalid_request(
                    Some("input"),
                    "DeepSeek V4 serve does not support tool results yet",
                ));
            }
        }
    }
    render_deepseek_v4_0731_messages_prompt(&messages, options)
        .map_err(|error| ServeError::invalid_request(Some("input"), error.to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::serve::items::parse_request;
    use crate::serve::render::{split_preopened_reasoning, split_reasoning};
    use serde_json::json;

    fn request(body: serde_json::Value) -> ServeRequest {
        parse_request(&body).expect("request parses")
    }

    #[test]
    fn chat_mode_closes_thinking_and_is_not_preopened() {
        let request = request(json!({"model": "ds", "input": "hi"}));
        assert!(!preopens_reasoning(&request).unwrap());
        let prompt = render_deepseek_v4_serve_prompt(&request).unwrap();
        assert!(
            prompt.ends_with("</think>"),
            "chat mode preclosed: {prompt:?}"
        );
        // Ordinary chat output carries no tags: the existing splitter is right.
        let split = split_reasoning("plain answer");
        assert_eq!(split.reasoning, None);
        assert_eq!(split.visible, "plain answer");
    }

    #[test]
    fn thinking_tier_preopens_and_headless_split_recovers_reasoning() {
        let request = request(json!({
            "model": "ds", "input": "hi", "reasoning": {"effort": "high"},
        }));
        assert!(preopens_reasoning(&request).unwrap());
        let prompt = render_deepseek_v4_serve_prompt(&request).unwrap();
        assert!(
            prompt.ends_with("<think>"),
            "thinking mode pre-opens: {prompt:?}"
        );

        // The model emits headless reasoning; the naive splitter would call
        // all of it visible, which is exactly the S3 hazard.
        let emitted = "weigh the options\n</think>\n\nThe answer is 5.";
        let naive = split_reasoning(emitted);
        assert_eq!(naive.reasoning, None, "naive split misclassifies (hazard)");
        let headless = split_preopened_reasoning(emitted);
        assert_eq!(headless.reasoning, Some("weigh the options\n"));
        assert_eq!(headless.visible, "\n\nThe answer is 5.");
        assert!(headless.closed);
    }

    #[test]
    fn preserved_history_round_trips_verbatim_for_checkpoint_identity() {
        // Turn 1 emission, headless.
        let emitted = "step one\n</think>\n\nFive.";
        let split = split_preopened_reasoning(emitted);
        let turn2 = request(json!({
            "model": "ds",
            "reasoning": {"effort": "high"},
            "input": [
                {"role": "user", "content": "Add 2 and 3."},
                {"type": "reasoning", "content": split.reasoning.unwrap()},
                {"role": "assistant", "content": split.visible},
                {"role": "user", "content": "Now add 10."},
            ],
        }));
        let prompt = render_deepseek_v4_serve_prompt(&turn2).unwrap();
        // History must contain the exact generated bytes so the completed
        // checkpoint's token prefix extends cleanly.
        assert!(
            prompt.contains(emitted),
            "history lost byte identity: {prompt:?}"
        );
        assert!(prompt.ends_with("<think>"));
    }

    #[test]
    fn unknown_effort_and_tool_items_fail_closed() {
        let bad = request(json!({
            "model": "ds", "input": "hi", "reasoning": {"effort": "medium"},
        }));
        let error = render_deepseek_v4_serve_prompt(&bad).unwrap_err();
        assert_eq!(error.param.as_deref(), Some("reasoning.effort"));

        let tools = request(json!({"model": "ds", "input": [
            {"role": "user", "content": "go"},
            {"type": "function_call", "call_id": "c", "name": "f", "arguments": "{}"},
            {"type": "function_call_output", "call_id": "c", "output": "r"},
        ]}));
        let error = render_deepseek_v4_serve_prompt(&tools).unwrap_err();
        assert!(error.message.contains("does not support tool"));

        for x_qwen in [
            json!({"no_thinking": true}),
            json!({"history_thinking": "strip"}),
        ] {
            let unsupported = request(json!({"model":"ds", "input":"hi", "x_qwen":x_qwen}));
            assert!(render_deepseek_v4_serve_prompt(&unsupported).is_err());
        }
    }
}
