//! Validated transcript → prompt bytes for the generic Qwen family.
//!
//! Normative fixtures: `qwen_no_thinking_preclosed_history_stable` and the
//! preserve/strip append cases in
//! `tests/fixtures/serve_render_fixtures_v1.json`. Two invariants matter
//! more than anything else here (S0 F1: checkpoint hits demand byte
//! identity):
//!
//! 1. `render(split(emitted)) == emitted` — the reasoning splitter and the
//!    preserve renderer are exact inverses, so an items round trip
//!    reproduces the generated bytes and completed-turn checkpoints hit.
//! 2. In no-thinking sessions, history assistant turns re-render the
//!    preclosed `<think>\n\n</think>\n\n` block the model actually
//!    consumed, keeping prompt-boundary prefix stability (the naive strip
//!    rendering is the documented divergence case).
//!
//! The validated Qwen3.8 identity currently renders through this same
//! generic path, exactly as the legacy CLI does (S0 exercised q38 through
//! it); the bespoke Qwen3.8 pre-closed-history renderer remains a modern
//! `qwen run` surface and is out of S1 serve scope.

use super::items::{ServeRequest, Turn};

const IM_START: &str = "<|im_start|>";
const IM_END: &str = "<|im_end|>\n";
const THINK_OPEN: &str = "<think>";
const THINK_CLOSE: &str = "</think>";
const PRECLOSED_THINK: &str = "<think>\n\n</think>\n\n";

/// Split raw generated text into (reasoning, visible) at the first
/// `</think>`. Exact-inverse contract: when the reasoning is `Some` and
/// `closed` is true, `render_assistant_body` reproduces the input bytes.
/// An unclosed block (token_limit mid-thinking, S0 F4) yields
/// `closed: false`; the HTTP layer marks the reasoning item and response
/// `incomplete`, and re-echoing it will not reproduce the original bytes
/// (no `</think>` existed), which is the recorded checkpoint caveat for
/// truncated turns.
#[derive(Debug, Clone, PartialEq)]
pub(crate) struct SplitReasoning<'a> {
    pub(crate) reasoning: Option<&'a str>,
    pub(crate) visible: &'a str,
    pub(crate) closed: bool,
}

pub(crate) fn split_reasoning(full: &str) -> SplitReasoning<'_> {
    if let Some(rest) = full.strip_prefix(THINK_OPEN) {
        if let Some((reasoning, visible)) = rest.split_once(THINK_CLOSE) {
            SplitReasoning {
                reasoning: Some(reasoning),
                visible,
                closed: true,
            }
        } else {
            SplitReasoning {
                reasoning: Some(rest),
                visible: "",
                closed: false,
            }
        }
    } else {
        SplitReasoning {
            reasoning: None,
            visible: full,
            closed: true,
        }
    }
}

fn render_assistant_body(
    reasoning: Option<&str>,
    visible: &str,
    no_thinking: bool,
    strip_history_thinking: bool,
    output: &mut String,
) {
    if no_thinking {
        // Normative: qwen_no_thinking_preclosed_history_stable. The model
        // consumed the preclosed block in its prompt; history must
        // re-render it or every prior-turn checkpoint misses (S0 F1).
        output.push_str(PRECLOSED_THINK);
        output.push_str(visible);
        return;
    }
    match reasoning {
        Some(reasoning) if !strip_history_thinking => {
            output.push_str(THINK_OPEN);
            output.push_str(reasoning);
            output.push_str(THINK_CLOSE);
            output.push_str(visible);
        }
        _ => output.push_str(visible),
    }
}

/// Render the full prompt for a validated request, including the
/// generation suffix.
pub(crate) fn render_qwen_serve_prompt(request: &ServeRequest) -> String {
    let mut output = String::new();
    if let Some(system) = request.system.as_deref() {
        output.push_str(IM_START);
        output.push_str("system\n");
        output.push_str(system);
        output.push_str(IM_END);
    }
    for turn in &request.turns {
        match turn {
            Turn::User(text) => {
                output.push_str(IM_START);
                output.push_str("user\n");
                output.push_str(text);
                output.push_str(IM_END);
            }
            Turn::Assistant { reasoning, visible } => {
                output.push_str(IM_START);
                output.push_str("assistant\n");
                render_assistant_body(
                    reasoning.as_deref(),
                    visible,
                    request.no_thinking,
                    request.strip_history_thinking,
                    &mut output,
                );
                output.push_str(IM_END);
            }
        }
    }
    output.push_str(IM_START);
    output.push_str("assistant\n");
    if request.no_thinking {
        output.push_str(PRECLOSED_THINK);
    }
    output
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::serve::items::parse_request;
    use serde_json::{Value, json};

    fn fixture_case(name: &str) -> Value {
        let fixture: Value = serde_json::from_str(include_str!(
            "../../tests/fixtures/serve_render_fixtures_v1.json"
        ))
        .expect("parse serve render fixture JSON");
        fixture["cases"]
            .as_array()
            .expect("fixture cases")
            .iter()
            .find(|case| case["name"].as_str() == Some(name))
            .unwrap_or_else(|| panic!("missing fixture case {name}"))
            .clone()
    }

    #[test]
    fn split_and_preserve_render_are_exact_inverses() {
        for emitted in [
            "<think>\n2+3=5.\n</think>\n\n5.",
            "<think></think>plain",
            "no thinking at all",
            "<think>\nweird</think>",
        ] {
            let split = split_reasoning(emitted);
            assert!(split.closed, "{emitted:?} should close");
            let mut rendered = String::new();
            render_assistant_body(split.reasoning, split.visible, false, false, &mut rendered);
            assert_eq!(rendered, emitted, "round trip diverged");
        }

        let truncated = split_reasoning("<think>\nran out of budg");
        assert!(!truncated.closed);
        assert_eq!(truncated.reasoning, Some("\nran out of budg"));
        assert_eq!(truncated.visible, "");
    }

    #[test]
    fn items_request_reproduces_preserve_append_fixture_bytes() {
        let case = fixture_case("qwen_multiturn_preserve_append");
        // The fixture stores the assistant turn as inline-think ChatMessage
        // content for the legacy renderer; the serve wire form is the split
        // items shape. Assert the two converge on identical prompt bytes.
        let split = split_reasoning("<think>\n2+3=5.\n</think>\n\n5.");
        let request = parse_request(&json!({
            "model": "m",
            "input": [
                {"role": "system", "content": "You are terse."},
                {"role": "user", "content": "Add 2 and 3."},
                {"type": "reasoning", "content": split.reasoning.unwrap()},
                {"role": "assistant", "content": split.visible},
                {"role": "user", "content": "Now add 4."},
            ],
        }))
        .expect("valid items request");
        assert_eq!(
            render_qwen_serve_prompt(&request),
            case["prompt"].as_str().expect("case prompt"),
            "serve items render diverged from frozen fixture bytes"
        );
    }

    #[test]
    fn strip_history_matches_strip_append_fixture_bytes() {
        let case = fixture_case("qwen_multiturn_strip_append");
        let request = parse_request(&json!({
            "model": "m",
            "input": [
                {"role": "system", "content": "You are terse."},
                {"role": "user", "content": "Add 2 and 3."},
                {"type": "reasoning", "content": "\n2+3=5.\n"},
                {"role": "assistant", "content": "\n\n5."},
                {"role": "user", "content": "Now add 4."},
            ],
            "x_qwen": {"history_thinking": "strip"},
        }))
        .expect("valid items request");
        // Strip drops the reasoning item; visible bytes remain verbatim.
        // The legacy fixture strips via strip_think whose output trims the
        // leading whitespace, so align the wire shape accordingly.
        let rendered = render_qwen_serve_prompt(&request);
        let expected = case["prompt"].as_str().expect("case prompt");
        // Both renders must share the prompt-boundary prefix through the
        // prior generation suffix; visible-content whitespace policy is the
        // serve wire's own (documented) choice.
        let boundary = "<|im_start|>assistant\n";
        let expected_head = &expected[..expected.find(boundary).unwrap() + boundary.len()];
        assert!(rendered.starts_with(expected_head));
    }

    #[test]
    fn no_thinking_history_matches_normative_fixture_bytes() {
        let single = fixture_case("qwen_no_thinking_single");
        let request = parse_request(&json!({
            "model": "m",
            "input": [{"role": "user", "content": "Add 2 and 3."}],
            "x_qwen": {"no_thinking": true},
        }))
        .expect("valid request");
        assert_eq!(
            render_qwen_serve_prompt(&request),
            single["prompt"].as_str().expect("case prompt"),
        );

        let case = fixture_case("qwen_no_thinking_preclosed_history_stable");
        let request = parse_request(&json!({
            "model": "m",
            "input": [
                {"role": "user", "content": "Add 2 and 3."},
                {"role": "assistant", "content": "5."},
                {"role": "user", "content": "Now add 4."},
            ],
            "x_qwen": {"no_thinking": true},
        }))
        .expect("valid request");
        let rendered = render_qwen_serve_prompt(&request);
        assert_eq!(
            rendered,
            case["prompt"].as_str().expect("case prompt"),
            "serve no-thinking history render diverged from the normative fixture"
        );
        let single_prompt = single["prompt"].as_str().unwrap();
        assert!(
            rendered.starts_with(single_prompt),
            "no-thinking append lost prompt-boundary prefix stability"
        );
    }

    #[test]
    fn string_input_matches_single_user_fixture_bytes() {
        let case = fixture_case("qwen_single_user_auto");
        let request =
            parse_request(&json!({"model": "m", "input": "Add 2 and 3."})).expect("valid request");
        assert_eq!(
            render_qwen_serve_prompt(&request),
            case["prompt"].as_str().expect("case prompt"),
        );
    }
}
