# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""GLM-5.3-Flash `qwen run` output contract (lane audit 2026-10-06, batch 2).

On one request, greedy, under the Metal debug layer:

1. Text chat prints the decoded generated bytes: identical to a raw run of
   the same rendered prompt (equal token fingerprints, equal stdout).
2. `--format responses` generates the same tokens and prints one Open
   Responses object whose reasoning and message reconstruct the text.
3. With a declared tool, text prints the generated tool syntax literally and
   `--format responses` publishes the call as a `function_call` item, from
   the same tokens.

Starts only its own `qwen` processes. Run detached for the full model.

  uv run scripts/reference/glm53/check_run_cli.py --binary target/release/qwen \\
    --model <gguf> --output <new dir>
"""

import argparse
import json
import os
import subprocess
from pathlib import Path

USER = "What is 2+2? Answer briefly."
PROMPT = (
    f"[gMASK]<sop><|system|>Reasoning Effort: Low<|user|>{USER}<|assistant|><think>"
)
TOOLS = {
    "tools": [
        {
            "name": "get_weather",
            "description": "Get the current weather for a city.",
            "parameters": {
                "type": "object",
                "properties": {"city": {"type": "string"}},
                "required": ["city"],
            },
        }
    ],
    "messages": [
        {"role": "user", "content": "What's the weather in Paris? Use the tool."}
    ],
}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--binary", type=Path, required=True)
    parser.add_argument("--model", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.mkdir(parents=True)
    env = dict(os.environ, MTL_DEBUG_LAYER="1", QWEN_METAL_LEASE_WAIT="1")
    base = [str(args.binary), "run", "-m", str(args.model), "--temp", "0"]

    def run(name, options):
        stats = args.output / f"{name}.stats.jsonl"
        command = base + options + ["--request-stats-jsonl", str(stats)]
        result = subprocess.run(command, env=env, capture_output=True, timeout=3600)
        (args.output / f"{name}.command.json").write_text(json.dumps(command))
        (args.output / f"{name}.stdout").write_bytes(result.stdout)
        (args.output / f"{name}.stderr").write_bytes(result.stderr)
        assert result.returncode == 0, (name, result.stderr[-2000:])
        assert b"Metal API Validation Enabled" in result.stderr, name
        return result, json.loads(stats.read_bytes())

    def fingerprint(document):
        return document["output_fingerprint"]

    text, text_doc = run(
        "chat-text", ["--user", USER, "--reasoning-effort", "low", "-n", "96"]
    )
    raw, raw_doc = run("raw", ["--raw-prompt", PROMPT, "-n", "96"])
    assert text_doc["usage"]["input_tokens"] == raw_doc["usage"]["input_tokens"]
    assert fingerprint(text_doc) == fingerprint(raw_doc)
    assert text.stdout == raw.stdout, (text.stdout, raw.stdout)
    chat = text_doc["diagnostics"]["glm5_next"]["chat"]
    assert chat["output"] == "text"
    assert chat["reasoning_closed"] is True, (
        "96 tokens should close a low-effort answer"
    )
    assert b"</think>" in text.stdout

    structured, structured_doc = run(
        "chat-responses",
        [
            "--user",
            USER,
            "--reasoning-effort",
            "low",
            "-n",
            "96",
            "--format",
            "responses",
        ],
    )
    assert fingerprint(structured_doc) == fingerprint(text_doc)
    assert structured.stdout.count(b"\n") == 1
    envelope = json.loads(structured.stdout)
    items = {item["type"]: item for item in envelope["output"]}
    reasoning = items["reasoning"]["content"][0]["text"]
    answer = items["message"]["content"][0]["text"]
    assert f"{reasoning}</think>{answer}\n".encode() == text.stdout, (
        reasoning,
        answer,
        text.stdout,
    )

    document = args.output / "tools.messages.json"
    document.write_text(json.dumps(TOOLS))
    tool_options = [
        "--messages",
        str(document),
        "--reasoning-effort",
        "low",
        "-n",
        "160",
    ]
    tool_text, tool_text_doc = run("tools-text", tool_options)
    tool_json, tool_json_doc = run(
        "tools-responses", tool_options + ["--format", "responses"]
    )
    assert fingerprint(tool_text_doc) == fingerprint(tool_json_doc)
    assert b"<tool_call>get_weather" in tool_text.stdout, tool_text.stdout
    calls = [
        item
        for item in json.loads(tool_json.stdout)["output"]
        if item["type"] == "function_call"
    ]
    assert len(calls) == 1 and calls[0]["name"] == "get_weather", calls
    city = json.loads(calls[0]["arguments"])["city"]

    report = {
        "status": "passed",
        "model": args.model.name,
        "text_equals_raw": True,
        "responses_reconstructs_text": True,
        "tool_call": {"name": calls[0]["name"], "city": city},
        "fingerprints": {
            "chat": fingerprint(text_doc),
            "tools": fingerprint(tool_text_doc),
        },
    }
    (args.output / "report.json").write_text(json.dumps(report, indent=2) + "\n")
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
